### ISSUE TITLE
Edit Planned Agreement Metadata

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1000]
### User Story
As an OPRE COR or team lead, I want to alter attributes of an overall agreement that has budget lines in "planned" status  so that I can have any necessary changes incorporated before it goes off to procurement.

### Preconditions
No budget lines are in “executing” status or above and there one or more budget lines in "planned" status. The contract is new and not continuing or a mod.

### Acceptance Criteria
- [x] User can change any agreement-level metadata for an agreement with BLs in planned status
- ~~Any user-supplied input should be tested and validated as for a new agreement, as in #675 (if done yet) or #775~~
- [x] After the user chooses to persist the changes to the agreement, the BLs' status should revert back to `Draft`
- [x] User should receive an indication of some kind that the edit was persistently stored and status changed successfully
-----------------------------------------

#### UX

- [ ]  Share designs with stakeholders and other OPRE team members for feedback
- [ ]  Refine the design based on feedback
- [ ]  Create clickable prototype
- [ ]  Provide design assets with annotations to developers

##### Backend
- [x] #1261 @xlorepdarkhelm 
  - Create Business Rules (gherkin features) for required field checks.
    - No budget lines are in “executing” status or above.
    - All BLIs are then set to DRAFT when the change happens.
  - Ensure Business Rules for metadata are checked for validity.
##### Frontend
- [x] If not already done, wire up the "Agreements List" edit button, to enter the Edit Agreement Detail
- [x] #1362
- [x] #1364

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- ~~Design/tech debt eliminated~~
- ~~Build process updated~~
- ~~Documentation updated or added~~
- ~~Feature flags/toggles created~~

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by jonnalley** [comment]
Someone asked this question earlier:

>Do we need a new wizard, or are we reusing the Create Agreement wizard, and passing in new click events (?)

For now we're doing the wizard as in #856 but with #1156, we're building a path to edit it without a wizard-like interface

**Comment by fpigeonjr** [comment]
> For now we're using the create wizard as in #856 but with #1156, we're building a path to edit it without a wizard-like interface

@jonnalley, is this still the case? Are we editing the Planned Agreement in the wizard or the new edit Agreement detail page?

**Comment by fpigeonjr** [comment]
@kimschulke / @andressacurvelo,
Would it be safe to assume that we would edit a PLANNED Agreement in the same way as  DRAFT one but with validation enabled as seen [here](https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=5007-160454&mode=dev)?

**Comment by jonnalley** [comment]
@fpigeonjr afaik edit Agreement detail page

**Comment by kimschulke** [comment]
Still kind of working through the best way to do reviews for every little change. We spoke with Team Leaders and Division Directors about this - whether or not changing a Team Member needs re-approval and etc. But we are still working through how to handle it. So for now, BLIs go back into Draft so they can be formally reviewed/approved again.

**Comment by fpigeonjr** [comment]
Think this one is mostly done since as seen here. Probably need to ensure that Agreements with BLIs in Executing or above are not editable though.

https://github.com/HHS/OPRE-OPS/assets/4629398/c4e8fca4-348c-400f-8394-c321f06d6596

**Comment by fpigeonjr** [comment]
@kimschulke @andressacurvelo, think this one is ready for UX review.

**Comment by kimschulke** [comment]
@jonnalley or @fpigeonjr or team - I am in Dev, but I cannot find an agreement with planned budget lines in order to test this.

**Comment by jonnalley** [comment]
@kimschulke try now. it shows up for me in staging. I suspect some concurrency issues were afoot yesterday, but could be mistaken

**Comment by jonnalley** [comment]
@kimschulke actually no never mind, your original statement is still the case, there's no agreements with planned budget lines that don't also have obligated lines which, rightfully so, is preventing you from editing....  

@fpigeonjr we need an agreement in the loaded data with just planned lines. Unless you beat me to it I might submit a PR with that data

**Comment by jonnalley** [comment]
Before I forget, I would think we need e2e testing added for this scenario to have this story properly tested out... ?

**Comment by jonnalley** [comment]
Ready in dev now, or in staging tomorrow

**Comment by kimschulke** [comment]
Running into some issues while testing..

I am logged in as a Basic User. I navigated to the Agreements List Page, and used the filters to find an agreement with BLIs in Planned Status. I selected the agreement titled "Interoperability Initiatives". The agreement has 2 BLIs in Planned Status. The Procurement Shop is currently NIH and I want to edit it to GCS. I click save and then I get an error.

<img width="1067" alt="Screenshot 2023-09-05 at 3 23 28 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/d4473277-af68-43f5-a1c1-833add3b2d0d">

**Comment by jonnalley** [comment]
@kimschulke as far as I understand it, a "Basic" user is essentially a "read only" user. you'll need to use the administer instead.  I created #1399 as a rant about this situation. :-)

**Comment by kimschulke** [comment]
Re-tested as an Admin User attempting the same edit described above. I was able to save the edit, but did not receive a success message. When I navigated to the BLI tab to see if the BLI Status updated from Planned to Draft, I found the success message. This message needs to be relocated to the page they land after they click save.

**Comment by kimschulke** [comment]
Additionally, side note for another user story... the project officer and team members may change throughout the life of the agreement. That information will need to remain editable on an agreement even when there are BLIs in Executing or Obligated. We will need to find a way to solve for that use case.

**Comment by fpigeonjr** [comment]
@jonnalley I think I am happy with the FE tasks completed here and checked off any related DOD items.

**Comment by jonnalley** [comment]
@fpigeonjr can we make that text change: `Agreement Edited - The agreement Agreement Name has been successfully updated.`

**Comment by fpigeonjr** [comment]
> @fpigeonjr can we make that alert text change: `Agreement Edited - The agreement Agreement Name has been successfully updated.`

yes I can work on this next

**Comment by jonnalley** [comment]
9/15
