### ISSUE TITLE
Modify planned budget lines

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1001]
### User Story
As an OPS user, I want to alter elements of a planned budget line in order to have my required funding needs met before the contract goes off to procurement.

### Preconditions
Existing budget lines on the existing agreement are in planned status.

### Acceptance Criteria
- [x] User can locate and choose to edit the agreement 
- [x] Only the user who originally created the budget line, the project officer, the contract team members, or a budget team member can modify a planned budget line
  - [x] This includes updating a note on a budget line
- ~~The user-supplied input should be tested and validated as for a new budget line, as in #675 (if done yet) and #674.~~
- [x] After the user chooses to persist the changes to the BL(s), the edited BL(s) status should revert back to `Draft` status
- [x] User should receive an indication of some kind that the edit was persisted

-----------------------------------------

#### UX
- [ ] Review research on #681
- [ ]  Explore design options
- [ ]  Share designs with OPRE stakeholders for feedback
- [ ]  Refine the design based on feedback
- [ ]  Meet with Developers to discuss design and interactions
- [ ]  Provide design assets with annotations to developers

##### Back End
- [x] #1276 @xlorepdarkhelm 
  - Only the user who originally created the budget line, the project officer, the contract team members, or a budget team member can modify a planned budget line
    - This includes updating a note on a budget line
- [x] #1379

##### Front End

- [x] #1374
- [x] #1375
- [x] #1386
- [x] #1446

### Definition of Done Checklist
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
~- [ ] Build process updated~
~- [ ] Documentation updated or added~
~- [ ] Feature flags/toggles created~

### Additional Context & Resources
* What happens if the original BL creator isn’t available to make updates (vacation, emergency, etc)? Who can make edits in that case?
* Why can’t other users make changes, and then those changes be just tracked for the audit trail ?

**Comment by xlorepdarkhelm** [comment]
Question: We currently do not have the concept of "teams" in the system. However the MVP is supposed to be for just the Budget Team. Do we need to actually establish what the Budget Team means in order to get the business logic right now, or does this get kicked down the road for post-MVP?

**Comment by fpigeonjr** [comment]
> submit a justification for making the change to the budget line and the justification persisted.

🤔Do we have a system/design for this?

**Comment by fpigeonjr** [comment]
> he user-supplied input should be tested and validated as for a new budget line

🤔Do we need validation since it will be reverted to DRAFT anyways?

**Comment by jonnalley** [comment]
@fpigeonjr on the justification, no, I assume it would just be using our notes on the agreement maybe?  That was a request from Sheila when we first wrote this.  has user feedback yielded anything different @kimschulke or @andressacurvelo ?

@fpigeonjr on the validation, I think I answered this in our conversation earlier, but yeah, shouldn't need any.

**Comment by fpigeonjr** [comment]
> Front End
>  - Add checks to allow editing BLIs in DRAFT or IN_REVIEW status but not others
>  - Add checks to allow editing of BLIs by authorized users

@jonnalley, do these FE tasks seem reasonable?

**Comment by xlorepdarkhelm** [comment]
Did we decide that this:

* If the amount is being changed, the user must be required to submit text for making the change and the justification should persist.

should be a separate story, as we need to figure out the notes situation?

**Comment by jonnalley** [comment]
@xlorepdarkhelm yes, we did. I just removed that AC.

**Comment by jonnalley** [comment]
@xlorepdarkhelm on that note though, presuming there's nothing else left to do here, please do go through and check off remaining AC and do the usual DoD review at your convenience please.

**Comment by fpigeonjr** [comment]
> User should receive an indication of some kind that the edit was persisted

added an FE task to address the this AC item. Hoping it won't require a refactor of the budget lines tab for the agreement detail but not ruling it out.

**Comment by jonnalley** [comment]
9/20
