### ISSUE TITLE
Wording on Create a Project

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1005]
### Goals
* Fix the wording on the alert that appears when user clicks cancel from the Create a Project workflow
* Fix the instruction text below "Select the Project Type"

### Tasks
- [x] Change options to "Cancel" and "Continue Editing"
- [x] Change instruction text below "Select the Project Type"

### Additional Context
* Currently providers the option to "Cancel" or "Cancel" but it should be "Cancel" or "Continue Editing"
* Instructions do not match Figma

**Comment by kimschulke** [comment]
**Currently in staging**
<img width="991" alt="Screenshot 2023-05-15 at 1 24 46 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/2520ea97-fa00-4faf-891b-0e7ad1c33ed5">

**Design in Figma**
<img width="816" alt="Screenshot 2023-05-15 at 1 25 00 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/3f0086cc-4c28-49c3-8453-4001f526094c">

**Comment by kimschulke** [comment]
Thank you @fpigeonjr ! Looks great!

One minor thing, when clicking cancel, the last letter in "Continue Editing" is not a part of the hyperlink

<img width="529" alt="Screenshot 2023-05-16 at 11 19 08 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/e4d0eb75-d709-4675-81b0-b5b6eb7293b2">

**Comment by fpigeonjr** [comment]
I think that is part of the Public Sans font @kimschulke. Here is a screenshot that show a link that includes a two `g`s and they are both not underlined.
<img width="1552" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/416f08cd-2f07-4eef-ae05-4f122f515005">
