### ISSUE TITLE
Wording for Cancel on Create a New Agreement

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1006]
### Goals
* Fix the wording for options displayed to user when they click cancel during the Create an Agreement workflow

### Tasks
- [x] Change options to "Cancel" or "Continue Editing"

### Additional Context
* Staging currently says "Continue" or "Cancel" but it should say "Cancel" or "Continue Editing"

**Comment by kimschulke** [comment]
**Currently in Staging**
<img width="569" alt="Screenshot 2023-05-15 at 1 39 35 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/9731fc05-228a-409a-b326-bf39879ff32e">

**Design in Figma**
<img width="513" alt="Screenshot 2023-05-15 at 1 39 41 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/65d522f1-418e-48b2-800d-bad3457944d6">

**Comment by kimschulke** [comment]
@fpigeonjr the button should be changed to "Cancel" and the secondary option is "Continue Editing"

**Currently in Staging**
<img width="620" alt="Screenshot 2023-05-16 at 11 21 39 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/c412cb86-a2a9-4724-b27d-c342b6eede26">

**Comment by kimschulke** [comment]
Font looks good, thanks!

**Comment by fpigeonjr** [comment]
> @fpigeonjr the button should be changed to "Cancel" and the secondary option is "Continue Editing"

PR coming soon.
