### ISSUE TITLE
Add % to Fee Rate in Creating New Agreement

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1019]
### Goals
* Add % to Fee Rate in Creating New Agreement

### Tasks
- [x] Add % to Fee Rate in Agreement Summary Card

### Additional Context
* The % shows up for positive numbers, but does not show up for 0%. On the previous page, where the user selects the Procurement Shop, it shows 0%. However on the agreement summary card it just says 0.  We should always include the % to keep things consistent.

### Definition of Done

- [ ] UI Review

**Comment by fpigeonjr** [comment]
@kimschulke Also noticed in the table that the fee is showing without a percent sign. Will take care of this with this PR.
<img width="1005" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/92a64bae-6a17-43e5-8cc9-799aea981bee">

**Comment by fpigeonjr** [comment]
> @kimschulke Also noticed in the table that the fee is showing without a percent sign. Will take care of this with this PR.

Nevermind this is a fee total not a percent.

**Comment by kimschulke** [comment]
Looks good - thanks!
