### ISSUE TITLE
Deleting a Draft Contract

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1036]
### User Story
As a team member on a contract, I want to delete a draft contract that I no longer need so that OPS doesn't have stale data. 

### Acceptance Criteria
- [x] A user has an option to delete a contract in draft status (a contract where all BLs are in draft state)
- [x] A user cannot delete a contract in any other status (BLs in any other status)
- [x] A contract with any budget lines other than draft status should not be able to be deleted
- [x] A user receives a warning before being able to confirm the deletion
- [x] Any (draft) budget lines associated with a contract being deleted are also deleted
- [x] Only a limited set of users should be able to delete a draft agreement
- [x] Deletion of a draft agreement and its budget lines is not a change in status, but an actual removal/deletion/expunging from the persistent store
- [x] The deletion event should be stored as an event in OPS's history/logging/audit trail mechanism(s)

-----------------------------------------

#### UX

- [x] Research needed on who ought to be able to delete a draft contract
- [x]  Explore design options
- [x]  Share designs with stakeholders and other OPRE team members for feedback
- [x]  Refine the design based on feedback
- [x]  Provide design assets with annotations to developers

##### Backend

- [x] #1074 @xlorepdarkhelm 
  - Only if agreement_type == AgreementType.CONTRACT
  - Only if all BLs are in draft state.
  - Reject if these cases is not true.
- [x] #1128 @xlorepdarkhelm 
  - Create Business Rules to capture the outlines rules
  - Create tests which validate the rules outline
- [x] #1238 @xlorepdarkhelm 
  - Ensure roles exist
  - Ensure role policies exist
  - Ensure role policies are enforced.
- [x] #1310

##### Frontend
- [x] #1294
- [x] #1299
- [x] #1307
  - [x] Optional - give Tooltip feedback on why DELETE is disabled (?)
- [x] #1313

### Definition of Done Checklist
- [x] UI works as designed (UX)
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [-] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [-] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by kimschulke** [comment]
This user story is to implement the Delete icon/button in the agreements list. The Delete icon/button appears on hover in the list or in the expansion panel when each row is expanded. Delete icon appears next to edit and send options.

**Design Screenshot**
<img width="581" alt="Screenshot 2023-06-02 at 9 23 53 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/3e30ff14-93af-41e5-b37d-303b5a91e3f7">

**Link to Figma**
https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=3492%3A92482&t=WQV0LuxlK3Y5cqin-1

**Comment by kimschulke** [comment]
**Here is what the user options (edit, delete, send) look like within the expansion panel**
<img width="580" alt="Screenshot 2023-06-02 at 9 33 23 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/2bf0a36c-7d0b-4daa-846a-606b50a3114e">


**Here is what the delete warning looks like**
<img width="571" alt="Screenshot 2023-06-02 at 9 33 40 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/4d9c4721-2c8c-4b09-96a9-6a25870fc6b0">

**Comment by jonnalley** [comment]
@kimschulke thank you for you note above. Did we hear from any DD or team lead on if there's any guidance on if or to whom deleting ought to be restricted to?

**Comment by kimschulke** [comment]
Attempting to complete the UX/UI Review, but running into some issues
1. Cannot login to dev. I can login to staging though.
2. When I am logged into staging, all the delete options are disabled. I tried creating a new test agreement to eventually delete, but the new agreement does not show up in the agreement list.

Can anyone help?  @fpigeonjr @jonnalley

**Comment by kimschulke** [comment]
UX/UI Review - looks good! One thing I am thinking about... The current success message for deleting an agreement says "Agreement Deleted" and "The agreement has been successfully deleted" 

Should it re-state the agreements name? For example: "Agreement ABC has been successfully deleted"

**Comment by jonnalley** [comment]
@kimschulke not sure who that question was directed to?  Do you have a preference?  Would we need to do that consistently if so?   What would be best for the user's experience ?  Ought we to wait for usability testing to answer this?  I realize I've raised more questions than I've answered. :pensive:

**Comment by kimschulke** [comment]
@jonnalley I will discuss with Andressa. I think for deleting, users might expect some greater confidence that the action they just took is the one they 100% wanted to take. Without seeing the agreement name, a user would have know way of knowing they deleted the right one. If we want to add to the backlog or pin for usability testing, thats ok too. I will start a google doc to track the usability topics that have come up recently.

**Comment by jonnalley** [comment]
@fpigeonjr @xlorepdarkhelm Please do evaluate and go through definition of done when you can please.

**Comment by fpigeonjr** [comment]
> Should it re-state the agreements name? For example: "Agreement ABC has been successfully deleted"

I can look at adding this today @kimschulke

**Comment by jonnalley** [comment]
review on 8/15

**Comment by jonnalley** [comment]
review on 8/15

**Comment by kimschulke** [comment]
Nice! Thank you @fpigeonjr ! I don't see this in dev yet, but I'm guessing it just hasn't been merged. One last thought, and unrelated to this user story, should we add the agreement name in all the success messages (creation, edited, etc)
