### ISSUE TITLE
UI issues on submitting for review approval

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1069]
- [x] Instruction text needs a small edit --

**Currently in Staging**
"Please review the agreement below or edit any information if necessary."

**Figma Design**
Please review the agreement below and edit any information if necessary. Send to Approval will send the agreement to your Division Director to review for Planned Status.

***

- [x] The spacing for Procurement Shop - There should be a space before and after the hyphen

**Currently in Staging**
Product Service Center-Fee Rate: 0%

**Figma Design**
DOI - Fee Rate: 4.8%

***

- [x] ~~the Review Page is missing the list of Team Members~~

***
~- [ ] Submit button~
The Submit for Approval button is still disabled so I think this user story might include enabling that option to complete the action. We might also want to include the ability to edit the agreement if necessary fields are required in order to submit. Right now, the Edit and Send to Approval buttons do not do anything. Clicking Edit should take them back to the data entry. Clicking Send to Approval should show the success message.

---

- [x] update to Reason to be formatted properly without underscore

--- 

- [x] Add Success Alert and redirect to Agreement list

**Comment by fpigeonjr** [comment]
I am seeing Team members after creating an Agreement with Team members.

**Comment by fpigeonjr** [comment]
> We might also want to include the ability to edit the agreement if necessary fields are required in order to submit. Right now, the Edit and Send to Approval buttons do not do anything. Clicking Edit should take them back to the data entry.

The Edit functionality has not been implemented so I added a simple alert to indicate that.

**Comment by fpigeonjr** [comment]
> Clicking Send to Approval should show the success message.
This is dependent on

**Comment by kimschulke** [comment]
Thank you Frank!

**Comment by fpigeonjr** [comment]
You bet @kimschulke. Thanks for reviewing this.
