### ISSUE TITLE
Agreement status tag is not displaying correctly

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1105]
think we broke the Agreements list status tag --- as discusses yesterday. I think the intent was to capture the lowest budget line status as the Agreement status but they all say Draft now.

<img width="1006" alt="SCR-20230613-itvg" src="https://github.com/HHS/OPRE-OPS/assets/4629398/c4cb8a47-9b7a-413f-a517-bf33c9fecf35">
<img width="1008" alt="SCR-20230613-ityb" src="https://github.com/HHS/OPRE-OPS/assets/4629398/b566e393-dbed-4212-af45-83da4ae0bdbb">

## Expected Behavior

I think the intent was to capture the lowest budget line status as Agreement status.

## Current Behavior

I think the intent was to capture the lowest budget line status as the Agreement status but they all say Draft now.

## Steps to Reproduce

1. Goto Agreements list and see all say DRAFT
2. Click into one and see budget lines are of different status
3.
4.

**Comment by jonnalley** [comment]
I don't know that something broke it later. I remember this has been broken since I first saw it with a populated list of agreements.

**Comment by jonnalley** [comment]
we need to add this to our test suite though clearly
