### ISSUE TITLE
Improve UX/Design onboarding materials

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#115]
### Goals
* As a project team without long-term UX/Design support, we want to be able to onboard new UX researchers/designers to the project efficiently so they can get up to speed and able to contribute quickly.

### Tasks
- [ ] Identify the types of info that would be helpful for a new UX/Designer to get up to speed.  For example:
  - User research
  - User personas
  - User scenarios / workflows
  - User feedback about their workflows (#119 )
  - Glossary
- [ ] Update the [UX/Design Onboarding doc](https://docs.google.com/document/d/1dTe12ZsUzAHjrXwCehRdckPMOnPe66S-kHDLT6Hu3ik/edit#heading=h.1vrm2xnfxd7s) with info on the above topics as you find and use existing resources and learn about the project

### Additional Context
* Most of the user types are presented [here](https://docs.google.com/presentation/d/1JkG6wlLBXInzsYTXjdPaNP3yn-XPHnRj5MloMwKb6lk/edit#slide=id.gd0fe4870b7_0_53), but additional types need to be added now that the scope has broadened and we've uncovered more use cases.

**Comment by juliaklindpaintner** [comment]
I _think_ this may be a thing that we do more gradually. It doesn't feel like a super useful thing to prioritize as a task in and of itself, but I think we can do this as we do other work, to some extent. I think I'm starting that work as I add to/reorganize the onboarding doc. I would keep this on a slow burn.

**Comment by ninamak** [comment]
Updated based on our conversation!
