### ISSUE TITLE
[8] Perform homogeneous migration of data with sample database (Oracle to Oracle)

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#120]
### Goals
* Test if we can use AWS DMS to migrate the data when the databases are in the same VPC and are of the same type (easiest case).

### Tasks
- [x] Migrate sequences/functions and triggers 
- [x] Migrate data using AWS DMS

### Acceptance of Criteria
- The data in our Oracle DB matches the data in the sample DB, inc sequences/functions and triggers

### Resources
- @carjug to add

### Additional Context
- Note: AWS DMS doesn’t migrate secondary indexes, sequences, default values, stored procedures, triggers, synonyms, views, and other schema objects not specifically related to data migration. 

**Overall purpose of testing with a sample DB:**

- Identify the steps and effort it takes to do the migration by practicing it
- Identify the AWS services we need to use
- Identify more targeted asks on getting ACF/HHS AWS permission, and add to our previous request
- Identify what we need from the vendor
- Identify the potential issues we may run into when migrating and perform early mitigation

**Comment by alexsoble** [comment]
Talking with @amymok about some smaller sub-tasks that ladder up to this work, one of them seems like:

"As a dev, I want to know the specific Oracle user privileges for the target database to be able to copy in the schema from a source database."

**Comment by amymok** [comment]
@alexsoble The subtasks you listed actually belongs to #74.  Moving it there.

**Comment by amymok** [comment]
I completed the process and noted the process in the [Steps to migrate (Oracle to Oracle) section](https://docs.google.com/document/d/1-sC6CKvfy-M8Gx77HWGyCZmmO8ilUTgCyz1yeau1lu0/edit#heading=h.akd6e7ktjn8v). @carjug @ninamak Ready for review.

cc @alexsoble

**Comment by ninamak** [comment]
@amymok Same comment here as on #74 .

Is there anything in particular it would be helpful for me to pay attention to when reviewing?  I read through the doc (super comprehensive!), and if the other devs feel it meets their needs, then LGTM!

The only thing I can think of: in the "Additional Context" section of this card, it says that some of the overarching goals of this migration testing work include:

> Identify the AWS services we need to use
Identify more targeted asks on getting ACF/HHS AWS permission, and add to our previous request
Identify what we need from the vendor

Did work on this particular card help you identify any of those things?

**Comment by amymok** [comment]
@ninamak Thanks for pointing those out.  Yes. this card helps with that, but I haven't been documenting everything since I am still in the process.  I do plan to add a new card after I finish with #183 to have a more comprehensive list of the needs.

**Comment by alexsoble** [comment]
Sounds like this work is complete and this issue can be closed out, am I right @amymok? 

@carjug looks like the "Carly Review" label is still on the issue. Want to remove the label and close this out, unless you have questions or issues that you want to raise?

**Comment by carjug** [comment]
It's good with me!
