### ISSUE TITLE
 Decide on Python dependency management tool

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#124]
### Goals

We want to use open-source Python libraries for our project, what's the best way to manage those dependencies? 

### Tasks

- [x] Review alternatives. Pipfile?
- [x] Make a decision

### Additional Context

Our "Hello World" app currently has a `requirements.txt` file. 

### Resources

N/A so far.

**Comment by alexsoble** [comment]
I'll pick this one up!

**Comment by alexsoble** [comment]
Relevant parts of the [cloudfoundry documentation](https://docs.cloudfoundry.org/buildpacks/python/index.html) for the Python buildpack:

> Cloud Foundry automatically uses this buildpack if it detects a requirements.txt or setup.py file in the root directory of your project.

...

> *Pipenv Support (starting in buildpack version 1.5.19)*
> To use Pipenv instead of pip (directly) for installing dependencies, place a Pipfile in the root directory. Easiest to let Pipenv generate this for you.

**Comment by alexsoble** [comment]
And here's what the [TTS Engineering Guide](https://engineering.18f.gov/python/#versions) has to say on the topic: 

> Finally, in an effort to ensure our deployments are repeatable, our code standards require all dependencies (including dependencies’ dependencies) be pinned to specific versions. This should also apply to the development environment (e.g. linters, testing tools, etc.) Suggestions for implementing that include
> * pip-tools’s pip-sync
> * pipenv’s Pipfile.lock
> * vendoring dependencies (though this is only a partial solution)

**Comment by alexsoble** [comment]
☝️ Based on the above, it looks like {Pipenv} or {pip with pip-tools} are the two leading contenders. 

Asked about this choice on Slack to see if I can draw out other relevant opinions/perspectives, because why not.

**Comment by alexsoble** [comment]
We met up this morning and made an engineering team decision to use Pipenv because of its security features, cloudfoundry support, and positive developer experience reviews from devs on and off the team. :gavel:

**Comment by alexsoble** [comment]
Will break out the "decision" and "set up" into separate issues here to have smaller and more atomic issues.

**Comment by alexsoble** [comment]
Broke out the setup piece into #132.

**Comment by alexsoble** [comment]
☝️ @amymok and @carjug and @ninamak — any objection to moving this card to "Done"?

**Comment by carjug** [comment]
LGTM!

**Comment by amymok** [comment]
Agreed!  This is "Done"!
