### ISSUE TITLE
No Team Member --- No Send to Review

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1243]
When sending an Agreement for Review, it will error if no Team Member is present in the Agreement.
## Expected Behavior

Should allow Agreements to be sent for review without team members?
## Current Behavior

When sending an Agreement for Review, it will error if no Team Member is present in the Agreement.
## Steps to Reproduce

1. Create an Agreement without Team member
2. Send to Approval
3. 😢 See error

## Context

Trying to create an Agreement without a team member.

localdev environment

**Comment by jonnalley** [comment]
@kimschulke @andressacurvelo feature or bug ?

**Comment by kimschulke** [comment]
I think this would get addressed during validation - the error messaging would outline they need to add a Project Officer and Team Members

**Comment by fpigeonjr** [comment]
@kimschulke The Project Officer validation is in place but not for Team Members due to Sheila's feedback.

**Comment by jonnalley** [comment]
fixed via PR #1246
