### ISSUE TITLE
DevEx/Tech Debt: Add a11y to eslint

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1249]
### Goals
add a11y checks as part of our linting strategy for eslint.

### Tasks
- [ ] _Key pieces of work that will need to be done to accomplish our goal(s)_

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by jonnalley** [comment]
7/8
