### ISSUE TITLE
View an agreement's note

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1301]
### User Story
As an OPS user, I want to view the user-inputted note for a given agreement as part of the agreements full details so that I can understand the entirety of human-supplied context not captured by atomic fields and attributes of the agreement.

### Preconditions
* The note added for a given budget line on the agreement is not in scope for this and is separate from an agreement's note
* The reason for changing metadata on an agreement will get handled in a separate user story

### Acceptance Criteria
- [ ] The user can perceive the "note" attributed to the agreement.
- [ ] The retention of the note should be exhaustive with no limit as to the age of the note
- [ ] The note wouldn't be editable by regular users accessing the OPS interface

-----------------------------------------

#### UX
- [x] Design already provided and discussed within #1156
- [x] Need to edit the current Notes section to a simpler "Note" field which displays the single note retained on that record, similar to the Description

#### Dev

- [x] Wire it up ?

### Definition of Done Checklist
- [ ] UI works as designed (UX)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* at the moment, the current page is showing some hard-wired note entries
* note is a 1:1 attribute of an agreement
* maybe a change justification concept will be implemented later for BLs and agreements ( #1431)
* Minimize and Simplify

**Comment by kimschulke** [comment]
The notes design has been updated on the Agreement Details page: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=5007-160454&mode=dev

For MVP, the Notes component will function the same as the Description component. There will be on text box that users can edit or add to as they see fit. The character limit has been increased from 150 to 750. In the future, we can explore retaining individual notes from different users at different times as opposed to a single persisting note.

**Comment by tdonaworth** [comment]
Ignoring potential future change, is there a specific reason for the character limit? Psychological (to incentivize the user to keep notes short?) Should this character limit be displayed/updated on edits? I see we specify a max, but no indication on whether they've exceeded that, or it should be a hard text limit (can't type past 750)? 

FYI - the DB already has this field set as "Text", so there's no character limit on the storage side.

**Comment by kimschulke** [comment]
I imagined it would just stop you from typing once you reach the limit, but open to discuss. Keeping it longer because we are removing their ability to write multiple notes so this would allow them to track history in whatever way they need - then we can see/learn from how they are using it to design a better solution moving forward. So, leaving it more open in order to learn. If we cut the limit to 150, we wont be able to learn from what they cannot write. That was my thought anyway.

**Comment by tdonaworth** [comment]
I agree with increasing it, especially given the use case, more curious why not just make it unlimited ♾️

**Comment by kimschulke** [comment]
I suppose! I thinks its generally good to put some kind of parameter around all open text fields, but lets take it to PL tomorrow?

**Comment by jonnalley** [comment]
Consensus: 1000

**Comment by jonnalley** [comment]
@stevtek any other tasks left on this story?  If not, can you run through the DoD on this issue?  Thanks you!

**Comment by jonnalley** [comment]
9/27
