### ISSUE TITLE
Include/Exclude Drafts from Total Agreement Value

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1321]
### User Story
As an OPRE user (Team Leader, Division Director or Budget Team Member), I want to include or exclude draft budget lines so I can compare how my drafts will impact the total agreement value.

### Acceptance Criteria
- [x] User can choose to include or exclude draft budget lines from the total agreement value
- [x] The total agreement value will change depending on the user's selection to include drafts or not

-----------------------------------------

### UX Tasks
- [x] Explore design options
- [x] Review design options with team for feedback
- [x] Refine design based on feedback
- [x] Provide design assets to developers (Ready for Dev in Figma)

### Dev Tasks
- [x] #1211
- [x] move summary cards for "Budget Lines by FY" and "Agreement Total" from the Agreement details tab to the budget lines tab
- [x] Create new section header for Budget Lines Summary above the section header for Budget Lines
- [x] Add a toggle component to the Budget Lines Summary so the user can choose to include/exclude drafts from the summary cards
- [x] Move edit button from top of page to within the Budget Lines section

### Definition of Done Checklist
- [x] UI works as designed (UX)
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* This work will further evolve our work on #1156  
* After sharing the design for https://github.com/HHS/OPRE-OPS/issues/1156 with two Team Leaders, we received feedback that it would be helpful to include or exclude draft budget lines from the Total Agreement Value. This would help clarify the confusion on whether or not the total includes drafts, because now the user can choose directly.
* Additionally, to further improve the connection between the summary cards (Total Agreement Value and Budget Lines by FY) and the budget lines which are currently on a separate tab, we decided to re-locate the summary cards to the Budget Lines Tab instead of appearing on the Agreement Details Tab

**Comment by kimschulke** [comment]
After sharing the design for #1156 with two Team Leaders, we received feedback that it would be helpful to include or exclude draft budget lines from the Total Agreement Value. This would help clarify the confusion on whether or not the total includes drafts, because now the user can choose directly. 

Additionally, to further improve the connection between the summary cards (Total Agreement Value and Budget Lines by FY) and the budget lines which are currently on a separate tab, we decided to re-locate the summary cards to the Budget Lines Tab instead of appearing on the Agreement Details Tab

**Comment by jonnalley** [comment]
@fpigeonjr @stevtek what other tasks remain on this story ?

**Comment by fpigeonjr** [comment]
As far as I know the DRAFT toggle has not been started.

**Comment by kimschulke** [comment]
We are going to update the designs on the figma dev page shortly. I'll post a link here once they have been updated.

**Comment by kimschulke** [comment]
Per the Additional Context Section above: _to further improve the connection between the summary cards (Total Agreement Value and Budget Lines by FY) and the budget lines which are currently on a separate tab, we decided to re-locate the summary cards to the Budget Lines Tab instead of appearing on the Agreement Details Tab_

**Changes Required**

- move summary cards for "Budget Lines by FY" and "Agreement Total" from the Agreement details tab to the budget lines tab
- Create new section header for Budget Lines Summary above the section header for Budget Lines
- Add a toggle component to the Budget Lines Summary so the user can choose to include/exclude drafts from the summary cards
- Move edit button from top of page to within the Budget Lines section

See Figma comments for specific interactions or business requirements. Let us know if you have any questions!

Figma designs linked here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=5007-160454&mode=dev

**Comment by jonnalley** [comment]
10/2
