### ISSUE TITLE
Implement delete BLI in `BLIRow` component

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#1353]
- add confirmation Modal
- consider re-usable hook to delete BLIs
- add Alert after successfully deleting BLI

<img width="733" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/cbc3dd3f-8cbb-40a6-8bb9-936276ed895f">

<img width="968" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/45c73fc2-79f3-4298-910b-707676141dac">

**Comment by fpigeonjr** [comment]
talked it over with @jonnalley and this will be its own user-story
