### ISSUE TITLE
`BLIStatusSummaryCard`

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#1354]
<img width="617" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/c39bccf5-5c43-4480-8587-31dfcfb5eae2">

**Comment by fpigeonjr** [comment]
> The breakdown of BLIs by amount and percent within each status. This graph will change depending on their filter selections. If they filter on Draft's only, the other statuses will remain visible but show as $0

notes from Figma by @kimschulke
