### ISSUE TITLE
`BLITotalSummaryCard`

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#1355]
- update TablePageLayout to include summary cards
- add BL Total Summary Card
<img width="685" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/92d9f836-dede-4bee-b936-4e043e4acc8a">

**Comment by fpigeonjr** [comment]
> The total of all BLIs in the dataset below. This amount will change based on their filter selections

note from @kimschulke on the Figma
