### ISSUE TITLE
Implement CAN Info Model

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#137]
### Goals
* Implement CAN Info model

### Tasks
- [ ] Implement CAN Info model based on [CAN Info tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1853066578)

### Additional Context

- [Database Models Spreadsheet](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#)
- [ER Diagram](https://docs.google.com/drawings/d/106BT0UIW_-zmocmNWMoGbe4nVmHGU1fYfsQWnTccsiI/edit)
- Blocked by #133 

### Resources
* #91

**Comment by ninamak** [comment]
Covered by #93
