### ISSUE TITLE
Refactor/Optimize OpsDbHistory Design for Agreement History Queries

### ISSUE THREAD

**Issue by stevtek** [HHS/OPRE-OPS#1377]
During work on #1361 / #1300 several design changes to OpsDbHistory were discussed regard the design of OpsDbHistory and how we should query for Agreement History.

1. agreement_id column
2. JSONB Query
3. Lookup Table
4. Inheritance Table
5. Dynamic JSON in the Data
6. Continuum solves everything

option 2 was selected for now but we need to revisit this.
We need to determine what the long term design for history like this is.  If we stay with the JSONB query we'll need to at least add an index that works for Agreement History queries.

**Comment by jonnalley** [comment]
#1411 is very related to this
