### ISSUE TITLE
After the user chooses to persist the changes to the BL(s), the edited BL(s) status should revert back to `Draft` status

### ISSUE THREAD

**Issue by xlorepdarkhelm** [HHS/OPRE-OPS#1379]

**Comment by jonnalley** [comment]
@xlorepdarkhelm We're seeing that it's not just reverting the edited BL(s) to draft, it's reverting ALL planned BLs on that agreement back to draft.  Please refer to AC on the original story for any clarity

Kudos to @fpigeonjr 


https://github.com/HHS/OPRE-OPS/assets/928984/6cecffb4-28f3-419f-9119-bcc09aa54e6d
