### ISSUE TITLE
Implement CAN Amount Model

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#138]
### Goals
* Implement CAN Amount model

### Tasks
- [ ] Implement CAN Amount model based on [CAN Amount tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=979139056)

### Additional Context

- [Database Models Spreadsheet](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#)
- [ER Diagram](https://docs.google.com/drawings/d/106BT0UIW_-zmocmNWMoGbe4nVmHGU1fYfsQWnTccsiI/edit)
- Blocked by #136 and #137

### Resources
* #91

**Comment by ninamak** [comment]
Covered by #93
