### ISSUE TITLE
HHS AMS Login Issue

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1387]
Can't be sure, but still getting an `SSL_ERROR_HANDSHAKE_FAILURE_ALERT` on the HHS AMS Login. I saw this prior, and hoped it was temporary. Will create a ticket to see if this is something on the HHS side, or simply because we're trying to connect from an `http` localhost site.

![image](https://user-images.githubusercontent.com/56687505/262662180-e681db7f-89cb-44d1-a616-0c136e89b3ed.png)

Escalated to AMS Support: The AMS Helpdesk ticket number is 853834

_Originally posted by @tdonaworth in https://github.com/HHS/OPRE-OPS/issues/1304#issuecomment-1690335435_

**Comment by jonnalley** [comment]
Issue appears to be isolated to one endpoint/machine for now

**Comment by jonnalley** [comment]
The reporting user has advised they have remediated the issue successfully
