### ISSUE TITLE
System Admin editing agreement metadata is silently dangerous

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1400]
Admin users are able to make any change desired, but changes have unintended and undisclosed consequences.

## Expected Behavior
1. When an admin makes metadata-level changes to a contract (or other agreement type) that has budget lines that are in Obligated (or executing?) status, some more thought and care should go into how the BLs are affected, if at all. 

## Current Behavior
1. Currently, if a System Admin edits only an agreement's metadata, any BLs in `obligated` (or `executing`?) status get bumped down to `Draft` status with no notice or warning. 

## Possible Cause
1. Likely following business rules somewhere.

## Steps to Reproduce
1. From the agreements list, edit a `contract` (as opposed to other agreement type) have at least one obligated BL, such as ID 7 or 8.
2. Staying on the `Agreement details` tab, make a minor change such as adding or changing the text in the description or "note" and choose to Save Changes. 
3. Without seeing or knowing with any indication, the obligated BL(s) have now reverted back to Draft.  This is bad and should not be the case. 

## Context
Saw this in both `development` and `staging` on 8/24.

## Possible Implementation
I'm not sure what I'm proposing as the solution, but need to have something in place to protect someone with System Admin powers from doing something unintended or undesired. 

## Related
Maybe partially and potentially related to #1399

**Comment by kimschulke** [comment]
There will likely be a different edit process for agreements with BLIs in executing or obligated. I think, right now, the only edit situation we have designed is when making an edit on a draft or when making an edit on a planned BLI that goes back to draft. Thats all we have so far.

**Comment by jonnalley** [comment]
@kimschulke yup, understood. Just making you aware and also for considering unintended consequences

**Comment by xlorepdarkhelm** [comment]
#1404 fixes this.
