### ISSUE TITLE
Issue with BL/agreement pre-loaded data?

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1403]
The contracts with IDs 7 and 8 have some odd math happening with their fees on their budget lines.

## Expected Behavior
The budget line amounts plus their fees should consistently add up to correct totals regardless of location

## Current Behavior
On the agreement list page, agreement IDs 7 and 8 both show amounts of $524.

## Possible Cause
some data in a json file is bad somehow and worse yet, no testing or constraints are catching it and there's no dynamic match calculating it up in the first place?  :grimacing

## Steps to Reproduce
https://ops-dev.fr.cloud.gov/agreements
https://ops-dev.fr.cloud.gov/agreements/7/budget-lines
https://ops-dev.fr.cloud.gov/agreements/8/budget-lines

1. Access the agreement list, ideally for a freshly untouched deployment or run of the `data_tools` container and note the total values for agreements 7 and for MIHOPE * in the list. 
2. Click on either of the two agreements and click on the budget lines tab
3. Note that the lone budget line shows a fee of $2,499, not $24. and that the total for the BL shows $2,900 not $524.

## Context
Saw this in both the `dev` and `staging` environments as recent as 8/24

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVk1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a8aba08454ebb59079981a42a313443dc36b19c6/Screenshot%202023-08-25%20at%2002.39.40.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWc1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--872812e7ffe42a67db8017f0d630d463ce2d98bc/Screenshot%202023-08-25%20at%2002.40.08.png)

**Comment by xlorepdarkhelm** [comment]
#1404 fixes this.
