### ISSUE TITLE
Changing procurement shop on draft agreement 

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1405]
When a user changes the procurement shop on a draft agreement (contract) to one with a differing fee, the total dollar amount is then impacted for the overall agreement and its budget lines and that's reflected on the agreement list correctly but not in the BL details. 

## Expected Behavior
Dollar amounts for BLs and the agreement total should be both accurate and consistent

## Current Behavior
On the agreement list page, the total column is updating to reflect the new amount with the new procurement shop's fees. The budget lines tab of the agreement detail is not updating it seems. 

## Possible Cause
unsure

## Steps to Reproduce

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjQ1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6624e122d9c0bd59282a691bbc938f846e2436a6/Screen%20Recording%202023-08-25%20at%2003.09.33.mov)

## Context
Seen in `staging` environment as recently as 08/24

Not sure if any relationship to #1404

**Comment by xlorepdarkhelm** [comment]
Further context I found: Whenever we save the BLIs after they are edited, the procurement shop fees are resubmitted as a change. They are changing by being 1/100th of what they were before. So, if a fee was, for example, 0.05, the new fee being submitted is changed to 0.0005.

**Comment by xlorepdarkhelm** [comment]
I believe that this bug and #1404 might be the same problem.

**Comment by xlorepdarkhelm** [comment]
This is merged with #1404
