### ISSUE TITLE
Basic User should not be able to attempt to update Agreement metadata [FE]

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1416]
When logged in as Basic User, we should not allow user to make edits to Agreement metadata.
- backend validation is in place so it errors // good job @xlorepdarkhelm 
- frontend should disable UI elements not allowing user to attempt
- affects the Agreements list,  Agreement detail pages, and Agreement workflow?

## Expected Behavior
Frontend should disable UI elements not allowing user to attempt to modify Agreement metadata

## Current Behavior
User is able to attempt changes to Agreement metadata and then goes to error page

## Steps to Reproduce
- login as basic user
- goto agreement one
- add a note or any change
- save
- goto error page
- 😢

**Comment by fpigeonjr** [comment]
> Only the user who originally created the ~~budget line~~ agreement, the project officer, the contract team members, or a budget team member can modify ~~a planned budget line~~ an agreement

qq: @jonnalley Would the agreement metadata rules be similar to the rules on the budget lines as seen on #1001?

**Comment by jonnalley** [comment]
@fpigeonjr yes, I believe so. not just similar, but the same, ideally. :-)

**Comment by kimschulke** [comment]
Created a design/debt github issue to refine/improve the tooltip message/reason for disabling the actions on hover. There are a few things we need to discuss/decide as a team that have been documented there

https://github.com/HHS/OPRE-OPS/issues/1470
