### ISSUE TITLE
Unable to Edit Agreement / Resolve Errors for Send to Approval

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1417]
When viewing the Agreement List, I click the send icon and it takes me to the validation page. It shows one error that the "Project Officer is required information". However, when I go to click edit and resolve the issue, the edit button is disabled so I cannot resolve anything.

## Expected Behavior

Edit button should be enabled when there are errors to resolve

## Current Behavior

Edit button is disabled

## Steps to Reproduce

1.
2.
3.
4.

**Comment by kimschulke** [comment]
<img width="1071" alt="Screenshot 2023-08-31 at 10 34 17 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/2f27f248-8268-4740-bcb1-53512b639953">

<img width="1046" alt="Screenshot 2023-08-31 at 10 34 03 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/307768de-089f-4ca8-9760-2b4e1032ba83">

**Comment by jonnalley** [comment]
so that's an interesting one. it really shouldn't be letting you send that agreement to approval and even getting to that screen IMO because the only BL it has is an obligated one....    The fact that it only has an obligated BL is the reason why you can't edit

**Comment by kimschulke** [comment]
Oh nice, good point. So, in that case the "send icon" should be disabled from the agreement list table. Maybe we just haven't hooked up all these requirements yet.

**Comment by fpigeonjr** [comment]
think maybe our test data may need an update. Not sure if an agreement would ever have a BLI that is obligated without having a PO?

**Comment by jonnalley** [comment]
wondering if #1428 will serendipitously fix this. time will tell

**Comment by fpigeonjr** [comment]
😄it's possible

**Comment by jonnalley** [comment]
confirmed this is no longer a problem
