### ISSUE TITLE
Update Portfolio Title Card

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1423]
### Goals
* Update the Team Leader tag on the Portfolio title card to match the most recent Figma design

### Tasks
- [x] Update the Team Leader tag
- [x] Add the label "Portfolio Description" above the description text

### Additional Context
* This change improves consistency across pages. In all other pages, we use tags for metadata so it did not make sense to have a different font treatment and icon/photo here.

### Resources
*Figma designs here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=5001-159899&mode=dev

**Comment by kimschulke** [comment]
**Previous Design**
<img width="776" alt="Screenshot 2023-09-01 at 1 17 39 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/f0c77289-7394-4ae2-9a5e-ccf5b5189f9c">


**New Design**
<img width="964" alt="Screenshot 2023-09-01 at 1 13 59 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/8e8e41e8-32e1-4019-94d9-a4acfd9a6d66">

**Comment by stevtek** [comment]
UX reviewed now (with Kim)
and merged to main

**Comment by jonnalley** [comment]
10/5
