### ISSUE TITLE
Character Limit on Table Content

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1438]
### Goals

- Apply a character limit to all table content and add a tool tip for full-content
- Character limit set to 50 characters for all content plus 3 dots "..." = 53 characters in total
- No content should go beyond 2 lines
- All table content should be centered aligned (not top aligned)

### Tasks
- [ ] _Key pieces of work that will need to be done to accomplish our goal(s)_

### Additional Context
- This change applies to all tables, especially any tables that have a long agreement name such as the Agreements List and BLI List
- An example of a very long agreement name is "Head Start: Recruitment, Selection, Enrollment, and Retention of Especially Vulnerable Families aka Head Start Reach: Strengthening Recruitment, Enrollment, and Engagement Practices for Families"

### Resources
*Figma link for example: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=6328%3A62138&mode=design&t=Jx4uJ2QKVajardEq-1

**Comment by kimschulke** [comment]
<img width="763" alt="Screenshot 2023-09-06 at 2 39 51 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/158f3853-5adc-4142-93ae-9646c1834ed4">

**Comment by tdonaworth** [comment]
Solution Draft: I could see us creating a text wrapper component for use in the `*TableRow` component. Simply wrap any text that is displayed with the data passed into the wrapping component, the component itself would then trim the text, add the "...", and then create a hover event containing the full data.

**Comment by kimschulke** [comment]
@tdonaworth that works too! We just want the data to fit within 2 lines, and if it goes beyond 2 lines, truncate the text and add the tool tip

**Comment by jonnalley** [comment]
11/7

**Comment by jonnalley** [comment]
11/7
