### ISSUE TITLE
Add Agreement Name or BLI Name into all success alerts

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1439]
### Goals
- In order to improve consistency, all success alerts should re-state the agreement name or BLI name within the alert

### Tasks
- [x] _Key pieces of work that will need to be done to accomplish our goal(s)_

### Additional Context
* This change should apply to any and all success alerts, especially the edit/delete functionality on the Agreements List, the edit/delete functionality on the BLI List, and the edit/delete functionality on the Agreement Details BLI Tab.
* Instead of saying "The agreement has been successfully updated" it would say "The agreement TITLE HERE has been successfully updated"
* This will improve the usability heuristic recognition rather than recall. By re-stating the agreement/BLI name, the user is not left wondering if they edited/deleted the correct item. They can confirm their action was correct by reading the success message.

### Resources
*Figma: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=5007%3A156806&mode=design&t=Jx4uJ2QKVajardEq-1

**Comment by kimschulke** [comment]
Example from Agreement List
<img width="767" alt="Screenshot 2023-09-06 at 2 48 31 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/668b3482-afa2-4595-8c17-1c8b296e59e1">


Example from BLI List
<img width="652" alt="Screenshot 2023-09-06 at 2 48 52 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/e7dffba0-44b6-481f-8b7f-3ec85542929e">

**Comment by fpigeonjr** [comment]
- Agreement edits

![Image](https://github.com/user-attachments/assets/160d807f-bf49-48bf-9e7b-24ec5388e720)

**Comment by fpigeonjr** [comment]
- Agreement deleted

![Image](https://github.com/user-attachments/assets/d1bce6e7-d55a-438a-ac42-782d3bebba6a)

**Comment by fpigeonjr** [comment]
- budget line created

![Image](https://github.com/user-attachments/assets/6f6c02e5-918c-4836-8f7e-c8a44b37319c)

**Comment by fpigeonjr** [comment]
- agreement created

![Image](https://github.com/user-attachments/assets/4d748f42-b169-4149-9300-de58922c7977)

**Comment by fpigeonjr** [comment]
- budget line edited

![Image](https://github.com/user-attachments/assets/347bae03-f3fa-460b-bb20-596d42f438c4)

**Comment by fpigeonjr** [comment]
- budget line deleted

![Image](https://github.com/user-attachments/assets/ec0e87cb-ee09-46e0-bdbd-351e5d87a2a6)

**Comment by fpigeonjr** [comment]
@kimschulke added some screenshots of the different cases and would be good to talk it over soon.

**Comment by fpigeonjr** [comment]
Agreement alerts
<img width="931" alt="image" src="https://github.com/user-attachments/assets/c6c7792e-20ad-4c00-b9bc-1600f935bf10">

**Comment by fpigeonjr** [comment]
Budget line alerts
<img width="941" alt="image" src="https://github.com/user-attachments/assets/e85c00eb-3414-4ffa-a797-ac5bc8396198">

**Comment by fpigeonjr** [comment]
- UX review on 8/27/24
