### ISSUE TITLE
Update tooltip message for disabled actions on All Agreements List

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1470]
### Goals
*Update the tooltip message on disabled actions to provide better insight into why something is disabled

### Tasks
* See #1430 for additional context.
- [ ] Confirm content/messaging
- [ ] Update the tooltip message

### Additional Context
*We have a temporary tooltip message in place, but it needs to be improved in order to 1) provide better context/reason why something is disabled and 2) be more consistent with phrasing for our other tooltips

### Resources
*https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=6620-43399&t=IwWIhGyPoO30F92i-4

**Comment by kimschulke** [comment]
Proposed design for tooltip message on disabled actions:

<img width="784" alt="Screenshot 2023-09-18 at 10 00 45 AM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/3ef95838-3cd8-463c-9f85-2775d3faaaaa">

**Comment by kimschulke** [comment]
To keep the message simple, I am suggesting "only team members listed on this agreement can edit, delete or send to approval"

A few considerations below --

Per our current business requirements, the only people who can edit/delete/send an agreement are:

- the person who created the agreement
- the project officer listed on the agreement
- the team members listed on the agreement
- the budget team

** Per discussions with Team Leaders and OPRE, we might also need to consider adding the Team Leaders associated with any CANs listed on the agreement and the Division Directors associated with any CANs on the agreement (there are various solutions/options on how to link these people with the agreement)


Technically, the budget team would be considered "team members" on every agreement since they support across OPRE. So I think the proposed message still works for that scenario.

One thing I'm not sure about is how to associate the creator of the agreement and their ability to edit, delete or send. Maybe the creator needs to add themselves as a Project Officer or Team Member in order to edit. I think in most cases, the Project Officer will be the one creating the agreement in the first place so this issue could potentially be a non-issue.


Lets discuss soon!

**Comment by tdonaworth** [comment]
> To keep the message simple, I am suggesting "only team members listed on this agreement can edit, delete or send to approval"
> 
> A few considerations below --
> 
> Per our current business requirements, the only people who can edit/delete/send an agreement are:
> 
> * the person who created the agreement
> * the project officer listed on the agreement
> * the team members listed on the agreement
> * the budget team
> 
> ** Per discussions with Team Leaders and OPRE, we might also need to consider adding the Team Leaders associated with any CANs listed on the agreement and the Division Directors associated with any CANs on the agreement (there are various solutions/options on how to link these people with the agreement)
> 
> Technically, the budget team would be considered "team members" on every agreement since they support across OPRE. So I think the proposed message still works for that scenario.
> 
> One thing I'm not sure about is how to associate the creator of the agreement and their ability to edit, delete or send. Maybe the creator needs to add themselves as a Project Officer or Team Member in order to edit. I think in most cases, the Project Officer will be the one creating the agreement in the first place so this issue could potentially be a non-issue.
> 
> Lets discuss soon!

Kim will do a separate writeup for this need.

**Comment by fpigeonjr** [comment]
reviewed with @kimschulke on 8/29/24
