### ISSUE TITLE
[FE] users not listed as team members on a contract can bypass permissions by using BL creation wizard 

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1475]
User demo was able to edit budget lines from the BLI workflow even though not a team member on the contract.
## Expected Behavior

For the frontend, basic users should not be allowed to attempt BLI edits when entering the create budget lines wizard unless they're a team member on the agreement the BL is on. 

## Current Behavior
Basic user is able to attempt to make edits to the buget lines from the create budgetlines wizard but the backend correctly sends an error. 

## Possible Cause
Frontend does not handle this use-case.

## Steps to Reproduce
1. Login as basic user from FakeAuth
2. Goto  create budget lines wizard
3. Select Agreement 1 // basic user does not have permission
4. Add a budget line
5. Submit Budget lines
6. ❗Error

**Comment by jonnalley** [comment]
“Standard” user in this context is referring to what is elsewhere referred to as a “basic” user which is essentially a read-only user. Not reflective of the standard use case or standard user role that will use OPS.

**Comment by fpigeonjr** [comment]
😄 correct, this one
<img width="571" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/70ca7dcd-72ee-4820-a84f-47a74a1cb371">

**Comment by fpigeonjr** [comment]
I'll update the title to reflect "Basic User"

**Comment by jonnalley** [comment]
verified this bug still is in place on`main` as of today's date

**Comment by fpigeonjr** [comment]
tested today and was unable to replicate the issue as seen below:

https://github.com/user-attachments/assets/4db35873-5994-48e9-b6a2-141e736dda74

**Comment by fpigeonjr** [comment]
- but I could add a budget line 😞

**Comment by jonnalley** [comment]
This GH issue was originally created back when the "basic user" was attributed to a role that was read-only (id 2). Since that time, the role has evolved and is no longer a read-only role but there's a different but related issue now.
