### ISSUE TITLE
Update `/login` to store `refresh_token` somewhere (along with `user_id` and expiration)

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1502]
Determine where to store the `refresh_token`:
- ( ) Store in backend, attached to user record?
- (x) Store in frontend, but in secure `HttpOnly` cookie?

Justification: Currently, we're storing the `refresh_token` openly in the `localStorage`, which isn't very secure. Since the `refresh_token` is used to generate new `access_token`s, it should be secured.

**Comment by jonnalley** [comment]
Curious how much overlap there is between this and the intent of #663
