### ISSUE TITLE
SPIKE: Rework frontend `config`

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1507]
### Goals
Currently our frontend contains quite a few "hard coded" configuration values. For dev, this has been fine, but as we transition, or need to implement more run-time configuration options (feature flags?) we'll need to handle this a little better.

### Experiments
- [ ] See what it would take to transition to a full React framework (Next.js, Gatsby, Grommet, etc), which have full support for `config` builtin.
- [ ] Try something like `react-runtime-config` as a shim for runtime configuration.
- [ ] something else...?

### Additional Context
* Up to this point, we had used the `create-react-app` to generate our application, and the build/run-time rely on the react-scripts. The few configurations we have, are injected at run-time via `REACT_ENV` vars (backend-api-uri). This doesn't support hot reloading nor realtime configuration. We'd like to expand on this.
* Now we no longer use CRA, but so making things more better is still needed

### Resources
* ???

**Comment by fpigeonjr** [comment]
might be related to  #2194
