### ISSUE TITLE
BL status change rejection

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1525]
### User Story
As a division director, I want to reject a request for budget lines so that my colleagues can go and make necessary changes and submit for review again. 

### Acceptance Criteria
- [x] The relevant approver should be able to reject budget line status change submissions
- [x] Taking this action should apply for any approval phase including but not limited to Draft->Planning, Planning->Executing, or the re-approval within Executing when a contract is initially awarded
- [x] In addition to the designated approver, the System Admin role should also be able to reject/decline the submitted change. 
- [x] The rejection is persisted and the user is notified of the status change
- [x] The contract's COR (aka Project Officer), if defined, is notified of the rejection
- [x] The budget line(s) in question should revert to the previous status before it went `In Review`
- [x] The relevant entries should be recorded in the event/history table(s) and be able to be properly rendered properly in the history of changes to the agreement ( #1300 )
-----------------------------------------

#### UX
- [x] Explore design options
- [x] Share design with team to discuss development considerations
- [x] Refine the design based on feedback
- [x] Share designs with stakeholders and other OPRE team members
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

### Definition of Done Checklist
- [x] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* The use case here would be that a team lead or DD doesn't know the edits to make themself or doesn't want to take the time to do it and doesn't want to leave the BLs or contract in limbo in the meantime.
* TODO: link to stories on approval steps

**Comment by stevtek** [comment]
I think this includes doing the Decline button for Draft-to-Planned (relates to #967)

**Comment by jonnalley** [comment]
> I think this includes doing the Decline button for Draft-to-Planned (relates to #967) as well as Planned-to-Execution (#1671)

@stevtek I'm not sure of what you meant really but to be clear, this button may be included in the designs you see in Figma that happen to be the same designs you're working off of for 965 and 967, however, those stories don't at all call for a process, functionality, or UI needed to reject or decline anything. That's what this story (1525)  is for.  We're trying to keep as much of a happy path as possible for now and at all times keeping our stories as narrow as feasibly possible.

**Comment by jonnalley** [comment]
01/26
