### ISSUE TITLE
Alert banner blocking user action/input

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1536]
When a success or error alert banner/message is being shown, any user input is blocked until the timeout is reached and the banner goes away

## Expected Behavior
The user should be able to still click on things or type when the alert/banners display.

## Current Behavior
Currently user input is blocked/not registered

## Possible Cause
dunno

## Steps to Reproduce
1. Create a new agreement
2. When you're redirected to the agreement list, try to click on any agreement in the list while the alert banner is still being displayed. 
3.
4.

## Possible Implementation
:shrug:

**Comment by fpigeonjr** [comment]
confirmed on 2/12

**Comment by fpigeonjr** [comment]
made improvements suggested from #2049
