### ISSUE TITLE
Agreement Meta Data

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1548]
- [x] Accordion
- [x] 2 column layout
- [x] e2e tests

<img width="942" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/65967c09-f463-436f-acb8-5505dd24a4f6">

**Comment by jonnalley** [comment]
@kimschulke  @fpigeonjr since the approver can't [yet](https://github.com/HHS/OPRE-OPS/issues/1522) edit directly from this screen, is that verb phrase and call to action something we want to still leave in place for now ?
