### ISSUE TITLE
Update Summary Cards on Create Budget Lines workflow

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1559]
### Goals
Update Summary Cards on Create Budget Lines workflow

### Tasks
- [ ] replace existing Summary Cards with the ones seen on the Agreement details Budget Lines tab

### Additional Context
* design debt from #1538 

### Resources

<img width="1140" alt="SCR-20231012-iobf" src="https://github.com/HHS/OPRE-OPS/assets/4629398/7756a323-ec43-4fa7-87c6-d4abed670223">
<img width="847" alt="SCR-20231012-iojs" src="https://github.com/HHS/OPRE-OPS/assets/4629398/df40a3ab-7b3d-41a6-87fd-2b6edcaadedf">

**Comment by jonnalley** [comment]
Figma links: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=6175%3A44166&mode=design&t=yfyrMxkq9YNGXGIA-1

**Comment by jonnalley** [comment]
This was completed earlier
