### ISSUE TITLE
Review & Approve BL status change from planned to executing

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1671]
### User Story
As an Approver for a budget line's corresponding division, I need to review and approve a contract's budget line(s) that is/are desired to advance to executing status so that proper oversight and governance over CAN funds are exercised

### Preconditions
* Assuming the reviewer was already notified that they need to review, ala #1471 for going into execution as prescribed in #677

### Acceptance Criteria
- [x] An approver can access and review the Budget line(s) submitted for review/approval
- [x] The approver should be able to review Agreement details, Budget lines, and CAN balances,
- [x] As part of the review process, an approver can be aware of how much remaining funds are available in the selected CAN(s) for the BLs.
- [x] The approver can review any notes/text left by the submitter
- [x] The approver can provide their own notes for their review and approval.
- [x] The approver can either cancel the review or attest to and commit their approval.
- [x] Upon approval, the requested budget lines should transition to `Executing` status and the user should be made aware of the successful change.
- [x] Upon approval, relevant entries should be recorded in the event/history table(s) and be able to be properly rendered properly in the history of changes to the agreement ( #1300 )

-----------------------------------------

#### UX
* See Figma ready for dev. UX tasks already done as part of earlier stories

#### Dev

**Frontend**

**Backend**

### Definition of Done Checklist
- [x] UI works as designed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* #677, #1603, #1501, #1471 are related stories
* Rejection aka declining is not in scope for this story and is handled in #1525
* Maybe post-MVP there will want to be an additional layer of approval?  TBD

**Comment by kimschulke** [comment]
Declining the submission will be developed through a separate github issue, right @jonnalley ?

**Comment by kimschulke** [comment]
Link to figma here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=7138-92198&mode=dev

**Comment by jonnalley** [comment]
1/23

**Comment by stevtek** [comment]
at this point, we don't have Research Type(s), Topics and populations studied, file attachments

**Comment by jonnalley** [comment]
@stevtek makes sense. Adjusted the AC accordingly, thank you

**Comment by kimschulke** [comment]
Tried to complete UI Review last week and this week, but I haven't been able to complete the tasks due to some bugs that are currently being worked out. Will come back to complete UI Review at another time.
