### ISSUE TITLE
Update data-import to insert records in version tables

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#1678]
### Goals

Our utility for inserting test data does not currently insert records in the _version tables.
Update the utility to allow for this.

Also, the many to many association tables are currently implemented with an archaic syntax that do not allow for versioning.  Since the JSON schema needs to be updated to implement the above, also update the syntax and versioning of the association tables.

### Resources

https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#association-object

**Comment by jonnalley** [comment]
11/30
