### ISSUE TITLE
Create an “override” check box, to indicate that a DD has acknowledged the planned expenditure exceeds the total available in the CANs.

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1800]
Not seeing this in the Figma and looking for some clarity on this.

**Comment by kimschulke** [comment]
@kimschulke  and @andressacurvelo investigating further, but not sure if this is necessary

**Comment by fpigeonjr** [comment]
thank you, would it be ok to remove this task from this user story - 967?

**Comment by tdonaworth** [comment]
Talked with OPRE team, and they indicated this is not needed.

**Comment by jonnalley** [comment]
We did discuss this with Sheila today and this particular task is not needed. removed as a task from #967
