### ISSUE TITLE
error saving Contract Agreements with contract_type

### ISSUE THREAD

**Issue by stevtek** [HHS/OPRE-OPS#1829]
Saving an agreement from the UI or REST where there is a value for contract_type (like RESEARCH) fails.

I think this is related to Enum fields being set to a string
The backend error is:
```
ops-backend      |   File "/usr/local/lib/python3.10/site-packages/marshmallow_enum/__init__.py", line 80, in _serialize
ops-backend      |     return value.name
ops-backend      | AttributeError: 'str' object has no attribute 'name'
```

For example our test record http://localhost:3000/agreements/1 has a contract_type.

**Comment by jonnalley** [comment]
1/2
