### ISSUE TITLE
Discuss test data needs for local development

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#184]
**Needs to be fleshed out**

### Goals
 
* A developer can pull down the code and have test data to explore and work with that will populate automatically into their local database. That data should be fake data as opposed to public records data.
* A developer can test that their code meets conditions of acceptance locally.
* A developer can run automated tests locally.

### Tasks

- Have a conversation about how we approach test data

**Comment by carjug** [comment]
Hey @ninamak @alexsoble what exactly should this proposal include/what form should it take? Is a one-to-two sentence comment on this issue enough?

**Comment by alexsoble** [comment]
That is a good question @carjug, I will defer to @ninamak here

**Comment by ninamak** [comment]
Not sure I can answer this question @alexsoble as this is the same question I was trying to ask you in our grooming mtg.  Happy to meet up to continue to talk through what would be useful here.  You indicated your calendar was pretty tight, so let me know when you have time.
