### ISSUE TITLE
Error creating history for error when table column missing

### ISSUE THREAD

**Issue by stevtek** [HHS/OPRE-OPS#1843]
Approve failed in demo (of deployed app) since the `workflow_step_instance` table was missing `updated_by`.
There was another error in the log saying it failed to create the history record for the error.

**Comment by stevtek** [comment]
unable to duplicate by just removing that `updated_by` column

**Comment by jonnalley** [comment]
@stevtek sorry for being dense.  Are you saying it's not an issue any longer ?

**Comment by stevtek** [comment]
I'm not certain, but maybe I should close this as "cannot duplicate" until I see this happen again.   There was an error in the logs of the deployed version when we were troubleshooting what turned out to be a missing column that said something about not being able to create the history record for the error.  I assumed that I could duplicate it by dropping the column and doing the workflow steps that errored during the demo, but I couldn't.
