### ISSUE TITLE
FY restrictions on BLI selection

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1848]
<img width="1207" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/a580bddf-5a0a-48ef-be65-0f7e1d911807">

AC

- [ ] However, the planned budget lines that are a candidate for selection must have a need by date in the current fiscal year or alternatively in the following fiscal year so long as the need by date is no more than 3 months away from the current date. The user should be made aware of this limitation.

> OSC2 is disabled because it's in a future year so it's not ready to be executed
> \- note from @kimschulke

**Comment by jonnalley** [comment]
@fpigeonjr see my comments in Figma and the contrast between what we see in the AC for this story

**Comment by fpigeonjr** [comment]
ack @jonnalley

So would this mean we need to allow for Need By Date 90 days past the end of the Fiscal Year? I added the AC from the parent story to this task.

**Comment by jonnalley** [comment]
I will close this out since we're scrapping this requirement.

**Comment by fpigeonjr** [comment]
Thanks @jonnalley
