### ISSUE TITLE
Incorporate Services Components into contract creation

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1852]
### User Story
As a COR, I want to create services components when I create a new contract, so that I can define the work the contract will include and its timing

### Acceptance Criteria
- [x] User can select if the contract is severable or non-severable as agreement metadata when creating a contract. Non-severable should be a default. This attribute shouldn't be changeable once any BL is in the executing state.
- [-] ~Users should be able to optionally provide a brief title for a services component they're adding.~
- [x] If the user selects that this is a severable contract, the user can define base and option years
- [x] If the user selects that this is a non-severable contract, the user can define SCs and OSCs
- [x] User can provide a description of the Service Component
- [x] User can provide a date-range (start / stop) for the Period of Performance [PoP]
- [x] Users aren't required to associate BLs to SCs at the time of contract creation
- [x] Users aren't required to create SCs at the time of contract creation and can skip it
- [x] Users can optionally specify a Contract Type at the time of contract creation

-----------------------------------------

#### UX

- [x] Review previous research completed for #1640. [Drawing of relationships](https://www.figma.com/file/ZclJ07uGZKS4pTwM006kg8/OPS-Diagrams?type=whiteboard&node-id=0%3A1&t=H1Su5oUQ2CSVwo0y-1)
- [x] Create design options
- [x] Review options/discuss considerations with internal team
- [x] Review options/discuss considerations with OPRE
- [x] Review options/discuss considerations with end users (CORs, Team Leaders)
- [x] Refine design based on feedback
- [x] Provide annotations, notes, and all design assets for development

#### Dev
Frontend
- [x] Service Requirement Type dropdown
- [x] Create Services Component Form—Create
  - [x] Services Component dropdown
  - [x] Period of Performance start date
  - [x] Period of Performance end date
  - [x] Description textbox
- [x] Services Component accordion—Read/Edit/Delete
  - [x] read SCs
  - [x] edit SCs
  - [x] delete SCs
- [x] #1967
- [x] #1961
- [x] #2042
- [x] #2018
- [-] ~Add Agreement Nickname for Step 2~
  - we need a separate story for this
- [x] Unit and E2E tests
- [x] #2071
- [x] #2076

Backend
- [x] #1864 @tdonaworth 
- [x] #1865
- [x] #1944
- [x] #1928
- [x] #2044
- [-] ~update `BLI.display_name` to `services_component.display_name`~
  - This won't work for BLIs that are part Agreements types without SCs or even ContractAgreements where the BLI has no SC.  We might could come up with some logic to handle all of this, but it might just be BLI#123 in the first iteration
  - we need to rework display_name when we do #2020 - I'm not sure if we need a separate ticket for display_name or if it's all a part of the same idea
- [ ] Create sample data
  - [-] ~update budgetline data to include `display_name` and/or `services_component_id` for all BLI page~
    - display_name is dynamic there's not data to load.  Currently it's just line_description but that needs to change
- [ ] All the tests!
  - [x] #2047
- [x] #2023
- [-] ~Add nickname property to Agreements~
  - we need a separate story for this 
- [x] #2030
- [x] #2039 
- [x] #2053 
- [-] #2054

UX Review

- 3/14/2024
  - [x] add confirmation modals on delete Services Components
- 3/7/2024
  - [x] Character limit for Agreement Title - set to 200 w/o helper text (we looked through the project catalog and the longest title was under 200)
  - [x] Character limit for Description - set to 1000 and add the helper text on Maximum characters
  - [x] Character limit for Notes - set to 500
  - [x] Change SC card color to white by default with a grey hover state (to match the BL interactions)
  - [x] Remove SC actions to edit/delete, but display on hover (to match the BL interactions)
  - [x] Updated content for cancel confirmation modal
  - [x] Updated content for cancel confirmation alert
- 3/5/2024
  - [x] scroll to top between steps in wizard
- 2/29/2024
  - [x] Remove Alert from Step 2 to Step 3 in Agreement create wizard
  - [x] Users should be able to save progress in-between steps of the process, so they can click Back to Step 2 from Step 3 and all of their BLs or SCs will still be there
- 2/28/2024
  - [x] Try to make components width consistent where possible (for example Services Component dropdown on SCs should be same as Services Component dropdown on BLs)
  - [x] Center align the text for “you have not entered any SCs or BLs”
  - [x] Add the “You have not added any Budget Lines Yet”

### Definition of Done Checklist
- [x] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources
* Draft Business Rules: https://docs.google.com/document/d/165NZTGL3yreqhDzzhAwcr0Hg-eWf1fN3mUfSI0zG0Uw/edit?pli=1

**Comment by kimschulke** [comment]
Feedback from Josh on dropdown options for Contract Type which is a new data field that will be added to the Agreement Details Step on Create New Agreement... sounds like it might need to be a multi-select

_

> There are a large number of Contract Types, but as we discussed the majority are ones that we would not see here at OPRE. I think that the following would be a safe middle ground to select as options:
> 
> Firm Fixed Price (FFP)
> Time & Materials (T&M)
> Labor Hour (LH)
> Cost Plus Fixed Fee (CPFF)
> Cost Plus Award Fee (CPAF)
> Hybrid (Any combination of the above)
>  
> 
> Contract type and severability do not have any interconnectivity, they are different items that need to be determined individually.

_

**Comment by jonnalley** [comment]
@kimschulke can you say more about the multi select ? From what I know there can only be one.

**Comment by kimschulke** [comment]
@jonnalley missed your comment - sorry for the delay - In Josh's response on Contract Type options he said it could be a Hybrid (Any combination of the above) - Lets bring it up with OPRE tomorrow (2/15)

**Comment by fpigeonjr** [comment]
> @jonnalley missed your comment - sorry for the delay - In Josh's response on Contract Type options he said it could be a Hybrid (Any combination of the above) - Lets bring it up with OPRE tomorrow (2/15)

Think that we resolved this to only be a single option for now(no multi-select) and also Hybrid is not for MVP. Is my understanding correct?

**Comment by jonnalley** [comment]
@fpigeonjr yes

**Comment by kimschulke** [comment]
A few design updates we need to reflect in dev

**Character limits**
- Character limit for Agreement Title - set to 200 w/o helper text (we looked through the project catalog and the longest title was under 200)
- Character limit for Description - set to 1000 and add the helper text on Maximum characters
- Character limit for Notes - set to 500

**SCs**
- Change SC card color to white by default with a grey hover state (to match the BL interactions)
- Remove SC actions to edit/delete, but display on hover (to match the BL interactions)

**Cancel**
- Updated content for cancel confirmation modal
- Updated content for cancel confirmation alert

**Comment by fpigeonjr** [comment]
👆@kimschulke I added these to the UX review section

**Comment by jonnalley** [comment]
3/19
