### ISSUE TITLE
Workflow lets invalid data be submitted for review

### ISSUE THREAD

**Issue by stevtek** [HHS/OPRE-OPS#1856]
Before workflows, when BudgetLineItemStatus was updated to UNDER_REVIEW to place drafts into review, there was server side validation enforced.  This needs to be added to workflow-submit and all the behavior tests need to be redone to test putting Agreements under review using workflows.

**Comment by jonnalley** [comment]
seems problematic.

**Comment by jonnalley** [comment]
consideration of the user's role
