### ISSUE TITLE
As a dev, I want my new PRs to come with a template

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#187]
### Goals
* Devs proposing new code know what info to include in PRs
* Reviewers reviewing code know what info they will use to review

### Tasks
- [ ] Write a proposed PR template
- [ ] Share with eng team
- [ ] 🚢 

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by alexsoble** [comment]
Picking up this small card at the end of the day since other cards are awaiting review or discussion-based.

**Comment by alexsoble** [comment]
@ninamak, this adds a PR template and is ready for your review! PR here: https://github.com/HHS/OPRE-OPS/pull/196

**Comment by ninamak** [comment]
@alexsoble Looks like this was already merged, but LGTM anyway!
