### ISSUE TITLE
Summary Cards don't update when editing BLs

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1873]
### Goals
- Connect the BL editor to the Summary Cards (Budget Lines by FY and Agreement Total)

**Current State**
- When you navigate to an Agreement Detail page and click Edit on the Budget Lines tab
- Hover over a budget line and click edit
- Edit the budget line amount and click Update Budget Line
- You will receive an alert that the BL has been successfully updated, however the Summary Cards do not update to reflect the new amount
- The Summary Cards will only update after you click Save Changes (this is not the intended interaction)

**Future State**
- When a BL is updated, the Summary Cards should display the update immediately after you click Update Budget Line
- For example, if you change the BL Amount from $1,000,000 to $500k, the totals displayed on the Summary Cards should decrease

### Tasks
- [ ] 
- [ ] 

### Additional Context
- This change is important because users need to be able to see the impact of their edits on the total
- The Summary Cards are intended to show the total of the data in the table below (as a summary). If they do not update when the user makes changes, they will not relate to the data below which might cause confusion

**Comment by kimschulke** [comment]
<img width="1022" alt="Screenshot 2024-01-16 at 3 12 56 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/6508dc38-18bb-4609-afaf-cad70c9b04eb">

**Comment by kimschulke** [comment]
The three cards on the bottom will be removed as they are left-overs from our previous design. Now that we have the 2 summary cards at the top, we no longer need the 3 cards on the bottom. I will create a separate GH issue to make that change and will post here shortly.

**Comment by jonnalley** [comment]
I tested this out today with numerous other variables not described here in the current dev/staging environment as of the time I'm writing this and this is no longer an issue. I'm presuming this was fixed with the three cards at the bottom went away and were replaced with the current layout.  Feel free to reopen if you find otherwise @kimschulke

**Comment by kimschulke** [comment]
Thanks @jonnalley! As long as the Agreement Total is dynamic with any changes submitted by clicking "Update Budget Lines", and not "Save Changes" this is good to go!
