### ISSUE TITLE
Fix Filter Across Multiple Pages

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1874]
### Goals
* Re-set data to page 1 when a filter is applied

Current State
- Navigate to BL list page and scroll through to the 2nd page
- Then apply a filter to the data (in the example, I filtered by Planned BL Status)
- The summary cards will update to show the filtered results, but the table will appear empty
- The table appears empty, but really the user is stuck on the 2nd page even though there is no 2nd page on the filtered results

Future State
- Whenever a filter is applied to the data, the data set should always start on page 1 of the data

### Tasks
- [ ] 
- [ ] 

### Additional Context
- See video below
- This change will prevent the user from thinking there are 0 results when there are results to show

**Comment by kimschulke** [comment]
https://github.com/HHS/OPRE-OPS/assets/65555918/b36a83c1-16ea-4431-8e79-6af732f98fe5

**Comment by jonnalley** [comment]
interesting.

**Comment by jonnalley** [comment]
1/17
