### ISSUE TITLE
UX Review 1/18/2024

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1889]
UX Review notes from @kimschulke 

Submitter

- [X] Update instructions in the Select Budget Lines accordion: Select the budget lines you'd like this action to apply to. The agreement will be sent to your Division Director to review and approve before changes are made.
- [x] Turn off toggle option when the user selects Planned to Executing
- [x] Turn off Review Changes accordion when user Selects Planned to Executing
- [x] Update instructions in the Review CANs accordion: The budget lines you've selected are using funds from the CANs displayed below.

Reviewer
- [x] Update header text to say: Approval for Executing Status or match the breadcrumbs
- [x] Update instructions for Review Agreement Details accordion: Please review the agreement details below to ensure all information is correct.
- [x] Update instructions for Review BL accordion: This is a list of all budget lines within this agreement. The budget lines showing In Review Status need your approval to change from Planned to Executing Status.
- [x] Update instructions for Review CANs accordion: The budget lines showing In Review Status have allocated funds from the CANs displayed below.
- [x] Add in “Other CANs Outside Your Division” under Review CANs accordion
- [x] Remove Review Changes accordion
-  Note to team for later: Review addtl info accordion will display Post-MVP
- [x] Update text on checkbox to say: I understand that approving these budget lines will start the Procurement Process
- [x] Update confirmation modal for approve to say: Are you sure you want to approve these budget lines for Executing Status? This will start the procurement process
- [x] Update confirmation modal for decline to say: Are you sure you want to decline these budget lines for Executing Status?

**Comment by fpigeonjr** [comment]
> Add in “Other CANs Outside Your Division” under Review CANs accordion

👆@stevtek do you remember where we landed on this?

**Comment by jonnalley** [comment]
@fpigeonjr I discussed with this Steve and Kim separately this week. If you can squeeze in any time to do so, can we throw together just a placeholder in the UI (not wired up) that reflects what's in Figma with some kind of brief indication it will be built out later akin to what we did for the research topics, etc..  If not, that's fine too, I might be able to carve out some time to later.

**Comment by fpigeonjr** [comment]
#1917 PR is ready for review

**Comment by tdonaworth** [comment]
> @fpigeonjr I discussed with this Steve and Kim separately this week. The fully-functioning thing will need to wait till CAN management. However, if you can squeeze in any time to do so, can we just throw together just a placeholder in the UI (not wired up) that reflects what's in Figma with some kind of brief indication it will be built out later akin to what we did for the research topics, etc.. If not, that's fine too, I might be able to carve out some time to later.

I know it's small, but I see this often - scope creep. I know the designs tend to show more than what's actually called out in stories, but we need to capture that as items in the story if it's a critical part. If not, backlog it.

**Comment by jonnalley** [comment]
@tdonaworth this was part of meeting an AC on 1671. To your very point, implementing it was deemed way too much for now and as has been done more recently, the ask was to put a minimal UI placeholder for the user and move on.
