### ISSUE TITLE
As an OPS team member, I want to read about our team meetings/ceremonies 

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#189]
### Goals

As an OPS team member, I want to read more about our team meetings/ceremonies so that I can ...

* refresh myself on the goal and intention of each meeting
* evaluate if our meetings are going well or not 
* do a gut check to see if we need to adjust our meeting content or cadence

### Tasks
- [ ] Bring together interested team members to talk about our current meeting/ceremony cadence 
- [ ] Update the Project README with any new information about goals and expectations (or link out from README to a separate doc)

 
### Additional Context

This is a small part of #169 and specifically a part of documenting and thinking about how work flows from "idea" to "done" on our team. 

### Resources

* From the project resources library: [REUSABLE: Sprint ceremonies](https://docs.google.com/presentation/d/1OyU8-PL4-iQ9P_K21OWuoYYgLdWTDSSOuGvehIzpfVk/edit#slide=id.g4b731387da_1_6)

**Comment by ninamak** [comment]
FYI @alexsoble that documentation about our team meetings/ceremonies was being captured in the [Project ReadMe](https://docs.google.com/document/d/1UQGQBCoiUzHSdpvyLQrS5GtTtQXjNrKHYy3y_SXED1k/edit#heading=h.n3gtfyokdfav) (which predates our GH setup).  Totally happy for it to live in GH moving forward if that would be useful, but at least this way you don't have to start from scratch.

**Comment by alexsoble** [comment]
@ninamak Thanks, good pointer! I updated the tasks to reflect that. Scheduling some time for us to talk about Planning.

**Comment by ninamak** [comment]
@alexsoble I'm realizing that I have a task on my To Do list that overlaps with this card.  I was supposed to rescheduled retros.  I think it makes sense to hold off on that and include it as part of this larger conversation.  Any objections?

**Comment by alexsoble** [comment]
I'm going to close this one out — if other team members want to pick this topic/theme back up in the future, they can always re-open
