### ISSUE TITLE
add service_requirement_type to ContractAgreement (for severable vs non-severable)

### ISSUE THREAD

**Issue by stevtek** [HHS/OPRE-OPS#1928]
<img width="1015" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/34590d6d-5f53-4dd1-afbc-3e8efcfdf1ed">

**Comment by fpigeonjr** [comment]
>Contract Type would have to be required in order for the UI to generate dropdown options under Services Components in the next step. Non-Severable = SC1, OSC2, OSC3 and etc. Severable = Base Period, Option Period and etc.

Figma comment from @kimschulke

**Comment by jonnalley** [comment]
@fpigeonjr you’re correct on your thought
