### ISSUE TITLE
Incorporate Services Components into viewing a contract

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1932]
### User Story
As a team member on a contract, I want to know and discern the services components on a given contract

### Acceptance Criteria
- [x] The user can view a contract's services components and how they relate to budget lines 
- [x] The user can view the SC's period of performance and description

-----------------------------------------

#### UX
- [x] Review previous research, if helpful https://github.com/HHS/OPRE-OPS/issues/1929
- [x] Update View Agreement Details design to include SCs
- [x] Share/discuss designs with Development
- [x] Add design to Dev Page
- [ ] Note annotations or comments as needed

#### Dev
- Front End
- [x] Update Agreement BL Tab to include SCs
- [x] #2088
- [x] Group BLIs by SC
- [x] 🐛 Fix Cancel Button (edit-mode)
- [x] align include Drafts toggle and edit icon

### Definition of Done Checklist
- [x] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources

**Comment by fpigeonjr** [comment]
@jonnalley is ok to close this issue?

**Comment by jonnalley** [comment]
3/20
