### ISSUE TITLE
Incorporate Services Components into editing a contract

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1934]
### User Story
As a contract team member, I want to be able to change services components information on a contract after a contract has been initially created

### Acceptance Criteria
- [x] User can make changes to the SC structure and relationship including adding new SCs, deleting SCs and moving BLs inside an SC
  - [x] deleting SCs should not delete associated BLs (BLs change to unassigned)
- [x] User should be able to change PoP dates on SCs
- [x] User can make changes to the Description on SCs
- [x] User can save and commit all changes
- [x] User should not successfully save and commit changes if they've removed SC1. A base year/SC1 is always required.  in what status(es) ??

-----------------------------------------

#### UX
- [x] Review previous research, if helpful https://github.com/HHS/OPRE-OPS/issues/1929
- [x] Update Edit Agreement Details design to include SCs
- [x] Share/discuss designs with Development
- [x] Add design to Dev Page
- [ ] Note annotations or comments as needed

#### Dev
- [x] add Services Component Form
- [x] List Services Components
- [x] add grouped BLIs by Services Component
- [x] add BLI form for CRUD operations
- [x] check Cancel and Save Changes button actions
  - these still work but not sure they make sense any more since changes are instant rather than grouped
- [x] validation: A base year/SC1 is always required.
  - propose we disable delete icon on SC 1
- [x] add DRAFT BLIS toggle
- [-] add/update tests

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

**Comment by fpigeonjr** [comment]
> * User should not successfully save and commit changes if they've removed SC1. A base year/SC1 is always required.  in what status(es) ??

@kimschulke Not sure on this one. Would it be ok to disable the delete icon on the Services Component 1?

**Comment by fpigeonjr** [comment]
UX Review on 3/27/2024
-  decided to not allow SC1 to be deleted once created by disabling delete icon
-  Remove “Required information” helper text on SC component. Add to instructions instead under form header

**Comment by fpigeonjr** [comment]
🤔 We need to think about how to handle the `Cancel button`. Some options include elevating state and bundling updates or caching the initial state of the Agreement and if they cancel revert to this original state.
- this may impact the agreement log as well

**Comment by jonnalley** [comment]
My 2 cents would be that unless there's a strong need to include cancelling in the AC and given that we are just trying to meet minimal user needs (but still be viable) for a happy path and given the non-trivial level of effort we've initially discussed and uncovered to implement this that maybe we ought to postpone this and come back to it another time.

**Comment by jonnalley** [comment]
3/26
