### ISSUE TITLE
Create backend design, to align `workflows` with Procurement Tracker

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1948]
Initial visual design created: https://lucid.app/lucidchart/fb021f39-168e-49cc-b2a1-0382aac916c2/edit?viewport_loc=-461%2C-26%2C2705%2C1395%2Cn2-.lMrupA.U&invitationId=inv_303cff8a-ce97-4eb1-9dfa-c4854c531118

Need to review and discuss with Engineers

**Comment by jonnalley** [comment]
workflows are no more
