### ISSUE TITLE
Add `ContactType` to `Contact` Model

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#1957]
# User Story

As an OPS Budget Team User, I want to designate the type of `Contact` for a `Vendor`.

# Acceptance Criteria

- [x] Add a `ContactType` enum with possible values `FINANCIAL`, `CONTRACT`, and `CUSTOMER`
- [x] Add a `contact_type` column to `Contact` with default `NULL`
- [x] If necessary, update migration script for `Vendor` and test data.

**Comment by jonnalley** [comment]
6/25
