### ISSUE TITLE
Remove Draft BLs from Agreement Total on Agreements List

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1959]
### Goals
*Draft BLs should NOT be included in the Agreement Total column on the Agreements List Page

### Tasks
- [ ] Exclude draft BLs from Agreement Total column on the Agreements List Page
- [ ] Update Agreement List instructional text to match content in Figma designs

### Additional Context
the Agreement List is intended to show totals without Drafts to give a more realistic view of the $ in play- whereas Draft is a space for what-ifs and placeholders that we don’t need reflected as a part of the agreement total - this will make it so the agreement list total always matches the agreement details total. 

### Resources
* [Design in Figma](https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=8957-109862&mode=design&t=y4C5fNqcXkRPQy0w-4)

**Comment by fpigeonjr** [comment]
> Update Agreement List instructional text to match content in Figma designs

Could use some clarity on this ac item @kimschulke @jonnalley

**Comment by fpigeonjr** [comment]
nm, think I found the answer to my question

![Image](https://github.com/user-attachments/assets/fca5d2f7-9fa4-491f-b3e3-8484ebfba947)

**Comment by fpigeonjr** [comment]
reviewed with @kimschulke on 8/29/24
