### ISSUE TITLE
FE: Contract Type (FFP, T&M, Cost+)

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1961]
<img width="726" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/a1493d05-b2bb-4b7a-9771-f483ed7b5a7d" />

Options for Contract Type include: 
Firm Fixed Price (FFP)
Time & Materials (T&M)
Labor Hour (LH)
Cost Plus Fixed Fee (CPFF)
Cost Plus Award Fee (CPAF)
Hybrid (Any combination of the above)

**Comment by fpigeonjr** [comment]
>Need to confirm with OPRE if this should be a multi-select or single select
>\-note from @kimschulke

**Comment by jonnalley** [comment]
@fpigeonjr I'm assuming you got your answer today :-)

**Comment by fpigeonjr** [comment]
Yes thanks @jonnalley. I heard that we won't need the hybrid option for MVP.
