### ISSUE TITLE
Discovery around Reviewing contract edits without BL status changes

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1985]
### Goals
Do initial research and experimentation to gain more understanding around a Division Director reviewing contract changes that need to be made, were already made, or in some cases approved, and LoE to change what we have now to accommodate.

-----------------------------------------

#### UX
- [x] Review previous research conducted in https://github.com/HHS/OPRE-OPS/issues/1929
- [x] Explore design options
- [x] Discuss options with developers and incorporate feedback
- [x] Share design options with OPRE
- [x] Refine design based on feedback
- [ ] Schedule feedback sessions with end users, if needed

### Additional Context & Resources
* A more-narrative document outlining potential scenarios and needs being addressed is [here](https://docs.google.com/document/d/1KIx2aFfZ9xvR_IgNNRtd-kOPtZk1_xxzkTP98-2aUSM/edit)
* * [Sequence Diagrams](https://lucid.app/lucidchart/1251eaf1-bccf-4e3a-a514-57ec20659621/edit?viewport_loc=-73%2C1385%2C2888%2C1381%2C0_0&invitationId=inv_ec912ed0-07b5-44ca-8086-c9c38b4e1be1)
* initial spike for making the changes itself is in #1964

### old Acceptance Criteria
- [ ] The user can be aware of and see submitted changes for review
- [ ] The user can review the agreement/BL entries before any changes as well as what the requested changes are 
- [ ] Any affected BLs for the contract do not change status
- [ ] This who/what of this approval is recorded and formatted properly in the contract and/or BL's history/audit

**Comment by kimschulke** [comment]
Reaching out to some DDs and Team Leaders to get additional feedback on our designs for the edit process and also the reviewer-approver side

**Comment by jonnalley** [comment]
4/18
