### ISSUE TITLE
NO PATCH if no state changes in Agreement Wizard

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2002]
In the Agreement edit wizard, should not submit a PATCH if no state changes in the agreement meta data from step 2 to step 3.

## Expected Behavior

Should go to step 3 without PATCH

## Current Behavior

PATCH happens and then we get an Alert saying Agreement was saved
## Possible Cause
Need to add a state check before sending PATCH

## Steps to Reproduce

1. Go to edit an Agreement wizard, like `/agreements/edit/1`
2. Continue Step 1
3. Continue Step 2 (without making changes)
4. 🔴 FAIL, PATCH submitted and Alert stating Agreement saved

## Detailed Description

https://github.com/HHS/OPRE-OPS/assets/4629398/5053a761-9b52-488a-96d3-f0aca8e7b393

**Comment by jonnalley** [comment]
Maybe will also fix #1960 as well ?
