### ISSUE TITLE
Add `ModType` to `BLI`

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#2008]

**Comment by rajohnson90** [comment]
Based on the following point from the data document:

> type_of_mode [sic. type_of_mod] is initially NULL until the BLI is in Execution.  The first “sub-status” is to “send a $0 requisition to the proc shop to let them know a mod is coming”.  Setting type_of_mod to “Mod - Admin” means that the COR is changing (or key personnel are changing) and the mod has no change to its funding.  Setting type_of_mod to “Mod - Amt TBD” means that we are negotiating with the proc shop and the BLI amount is currently unknown.  “Mod - As Is” means we are not changing the BLI in any way.  “Mod - Replacement Amt Final” means the amount has been changed to its final value.

It seems we will need the following values:
Admin
AmountTBD
AsIs
ReplacementAmountFinal
