### ISSUE TITLE
Unique budget line identifier

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2020]
### User Story
As an OPS user, in order to avoid confusion and to gain better understanding, I need to distinguish and  discern unique and distinct budget lines from one another as they go through their own separate and varying approval processes and can be categorized into services components. 

### Acceptance Criteria
- [x] When viewing budget lines in a contract broken down into services components, user can uniquely discern and reference any individual budget line whether just viewing contract details or undergoing a review or approval process.
- [x] User can uniquely reference and discern distinct budget lines in history/audit log event records
- [x] User can uniquely reference and discern distinct budget lines in relevant notifications 
- [x] Any unique characteristic of the BL ought to be directly immutable by the user. 

-----------------------------------------

#### UX

- [x] Update column in various UI tables

#### Dev

- [x] Decide on what we're doing about `displayName`, which will determine backend effort
- [x] update Budget Lines tables to reference unique id
- [x] updates Alerts and Modals to reference unique id

### Definition of Done Checklist
- [x] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [X] Design/tech debt eliminated
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources
* Sounds like DB ID is the way to go

**Comment by tdonaworth** [comment]
We use the term `uniquely discern` but in what context? Unique to the Agreement, Unique to the Division, Unique to the whole system?

**Comment by jonnalley** [comment]
> We use the term `uniquely discern` but in what context? Unique to the Agreement, Unique to the Division, Unique to the whole system?

😉 indeed. 😄 Seems like we have some decisions to make.

**Comment by fpigeonjr** [comment]
🍿

**Comment by fpigeonjr** [comment]
- went with `budgetLine.id` instead of `display_name` for now as seen in #2138

**Comment by fpigeonjr** [comment]
took a stab at updating the budget lines history log to show like: 
- `BL 27 created by Admin Demo`
- `BL 27 Need By Date changed from 6/13/2043 to 6/13/2025 by Admin Demo`

**Comment by jonnalley** [comment]
4/2

**Comment by fpigeonjr** [comment]
@jonnalley is it ok to close this ticket?
