### ISSUE TITLE
Add model `CANFiscalYearFundingDetails`

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#2058]
Notes taken from 3/6/24 Data Meeting:

> `MAPS.CAN.FUND`, `MAPS.CAN.ALLOWANCE`, `MAPS.CAN.ALLOTMENT_ORG`, `MAPS.CAN.SUB_ALLOWANCE`, `MAPS.CAN.CURRENT_FY_FUNDING_YTD` -
    Can all be considered together the funding details for the CAN - should be carried over into OPS

The model for [MAPS CAN ](https://github.com/HHS/OPRE-OPS-Data/blob/main/data/maps_ddl/MAPS/012-CAN.sql)

This task is about creating a `CANFiscalYearFundingDetails` model with the above columns (and a foreign key to `CANFiscalYear`)

For testing/development purposes, `MAPS.CAN.ALLOWANCE`, `MAPS.CAN.ALLOTMENT_ORG`, `MAPS.CAN.SUB_ALLOWANCE` can be represented as a string of 10 alphanumeric characters.
`MAPS.CAN.FUND` is 6 alphanumeric characters + 4 digit year + 4 alphanumeric characters

**Comment by jonnalley** [comment]
7/2
