### ISSUE TITLE
Improve success alerts on SC/BL editor

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2094]
### Goals
* Improve the success alerts on the SC/BL editor (within Create Agreement and from View/Edit Agreements)
* Right now, when a user adds, updates or deletes a BL or SC, they will receive a confirmation alert for that action. The current alert displays at the top of the page and forces the user's view/focus area to the top of the page which is disruptive to the workflow
* In the future, consider showing alerts in the area of the page the user is currently viewing and/or explore a smaller toast message that does not need to stretch across the entire page

### Tasks
- [ ]TBD

**Comment by jonnalley** [comment]
In some cases, it also blocks further user input as documented in #1536

**Comment by fpigeonjr** [comment]
think we may be able to close this one @jonnalley
