### ISSUE TITLE
Incorporate Cancel option into Send to Approval workflows

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2096]
### Goals
* Incorporate a Cancel option into the Send to Approval workflows

### Tasks
- [x] Add Cancel option into designs in Figma
- [x] Add Cancel option into dev

### Additional Context
- Anytime a user enters a new task/user workflow, we need to provide them a way to cancel or exit the process
- We forgot to include this in our initial designs

**Comment by fpigeonjr** [comment]
no I am not seeing a cancel option on the send to approval page

**Comment by fpigeonjr** [comment]
looks like this was addressed in the ReviewPage improvements. 

https://github.com/user-attachments/assets/74b4f378-f035-44b4-8345-6e9570aff248

**Comment by fpigeonjr** [comment]
@jonnalley I believe this issue can be closed but maybe we get UX review on the confirmation modal?

**Comment by fpigeonjr** [comment]
- UX Review on 8/27/2024
