### ISSUE TITLE
Incorporate SCs into Send to Approval workflows

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2097]
### Goals
* Incorporate SCs into Send to Approval workflows
* Currently, the Send to Approval workflow shows a table of BLs with an SC column, but does not show the groups of SCs as accordions that we added into the design later on

### Tasks
UX Tasks
- [x] Add SC's into designs in Figma for Send to Approval workflows

Dev Tasks
- [ ] 

### Additional Context
* 

### Resources
* #677
* #2349

**Comment by kimschulke** [comment]
@fpigeonjr have you guys completed development for this? I can't remember

**Comment by fpigeonjr** [comment]
> @fpigeonjr have you guys completed development for this? I can't remember

No @kimschulke not yet.

**Comment by jonnalley** [comment]
7/8
