### ISSUE TITLE
hard coded division directors and incorrect approvers in workflows

### ISSUE THREAD

**Issue by stevtek** [HHS/OPRE-OPS#2134]
The IDs of the division directors are hard coded in create_notification_for_division_directors
Also, the approvers are set in the template, so they can't be set to the correct approvers for a given BLI.  The template effectively hards codes them for all instances.

**Comment by jonnalley** [comment]
seems related to #2370

**Comment by jonnalley** [comment]
Did @stevtek's PR #2458 fix this ?

**Comment by stevtek** [comment]
I fixed this when converting workflows to status change requests as a part of #2316
and it's task #2465, PR #2467
