### ISSUE TITLE
Agreement Log: Deleting Budget Lines

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2145]
When deleting Budget Lines, the id does not show up in the Agreement History.

## Expected Behavior

When deleting Budget Lines, the id SHOULD not show up in the Agreement History.
maybe something like:
`BL 26 was deleted by Admin User`
## Current Behavior

When deleting Budget Lines, the id does not show up in the Agreement History.
currently states:
`Budget Line was deleted by Admin User`
## Steps to Reproduce

1. Goto Agreement BLI tab
2. Delete an BLI
3. Save
4. Go back to the Agreement details page
5. See History Log

## Detailed Description

https://github.com/HHS/OPRE-OPS/assets/4629398/f3c750c1-4d2e-4450-80f3-c37e4c944a2a

**Comment by fpigeonjr** [comment]
UX review item found on 4/2/2024 ref #2020

**Comment by jonnalley** [comment]
4/3
