### ISSUE TITLE
Budget Change: Edit BLs (including prompt for send to approval)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2193]
### User Story

As a COR or other team member, I need to edit budget-impacting details (CAN, Amount, Need By) of a budget line where the BL is already in `Planned` or `Executing` status, and know that it requires an approval, so that I understand how my edit will impact the overall budget.

### Preconditions

* A given contract has one or more budget lines in either `planned` or `executing` BLs

### Acceptance Criteria

1. On a given existing BL on a contract, authorized users are able to edit attributes of it and elect to persist the change without altering the status of the budget line. Authorized users would be limited to project officer, named team members, division director linked to associated CANs, budget team, and system admin. 
1. Before allowing any update to persist, all validations should still be enforced that were necessary to get the budget line in the current status (planned or executing). In example, amounts shouldn't be allowed to be changed to 0 or an empty string.
1. Additionally, before the update would persist, the user would be made aware of and to confirm that the change will need to undergo review and approval.
1. After successful persistence, the user is aware that the change is awaiting approval
1. Upon successful persistence, relevant entries should be recorded in the event/history table(s) of who made what changes when and this event should be properly rendered in the history of changes to the agreement.
1. User can choose to cancel making any changes and leave the pre-existing values for any metadata persisted.

-----------------------------------------

##### FrontEnd
- [x] #2261
- [x] Display Confirmation modal if budget changes are requested
- [x] handle `202` for change requests
- [x] #2323
- [x] #2324
- [x] in BLI Table, show BLIS in review with updated Tag
- [x] in BLI Table, show BLIS in review with detailed ToolTip
- [x] show requests in the Agreements Log
- [x] use `in_review` instead of `has_active_workflow` to indicate a BLI is under review
- [x] #2366
- [x] add additional validations on the BLI Form for budget rules in Tests below
- [x] allow EXECUTING BLIs to be edited
- [x] #2287
- [x] #2308
- [x] look at Alert messages and redirects after Cancel/Save actions
- [-] #2322
- [x] add/update unit/e2e tests as needed
- [x] #2325
- [x] #2359

##### BackEnd
- [x] Create a general ChangeRequest model and subclasses for types of changes
- [x] Change the existing edit endpoints (for BLI and Agreement) to create ChangeRequests conditionally and return 202 instead of 200
- [x] change-request-reviews endpoint to approve/deny a change request (not actually needed for this ticket)
- [x] #2238
- [x] #2312
- [x] add validation for budget rules in Tests below
- [x] #2380

### Tests (if not already in existence)
All of these tests should not change the status of the BL

* User setting a BL amount from a non-zero amount to 0
* User setting a BL amount to a negative amount
* ~User setting an `Executing` (not `Planned`) BL amount over the budget remaining CAN balance/budget shouldn't be allowed~
* ~User setting an `Executing` BL but changing the CAN and the amount at the same time (success and failure given above test)~
* ~Same tests but above but with `Planned` where there is no restriction on amount going over CAN balance~
* date changing tests - for a BLI that is `Planned` or `Executing` changing to remove the data date or change to a date in the past is not allowed

### Definition of Done Checklist
- [x] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [x] New design/tech debt documented (if applicable)
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* #1964
* A more-narrative document outlining potential scenarios and needs being addressed is [here](https://docs.google.com/document/d/1KIx2aFfZ9xvR_IgNNRtd-kOPtZk1_xxzkTP98-2aUSM/edit)
* [FigJam process visual](https://www.figma.com/file/ZclJ07uGZKS4pTwM006kg8/OPS-Diagrams?type=whiteboard&node-id=562-9038&t=3WZSkvmFRX8b2AU6-4) 
* [Figma dev-ready frame](https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=9203-79887&mode=design&t=ZacBPXo075AJy4Vs-4)

**Comment by fpigeonjr** [comment]
- added logix to capture BLI snapshot and compare to form state
- also tracking if BLI is PLANNED or EXECUTING
- confirmation modal is firing 
- seeing new props on BLI from the PATCH thanks to @stevtek

**Comment by fpigeonjr** [comment]
- updates In_Review `Tag`
- updates Alerts based on budget lines in review status
- allows for editing EXECUTING budget lines

**Comment by fpigeonjr** [comment]
- UX Review conducted on 5/4/2024 revealed that confirmation modal to send changes to Division Director should happen later in the flow.  User should be able to make temporary BLI changes and have the ability to cancel out of those changes and/or click Save changes and if they are financial changes then the confirmation modal should fire. 
-👆is captured in task #2238

**Comment by fpigeonjr** [comment]
UX Review conducted on 5/14/2024
- add `ToolTip` for TBD budget-lines
- look at `Alert` messages and redirects after Saving
- opportunity discovered for wizard state to be refactored with the `onFinish` function

**Comment by fpigeonjr** [comment]
- ToolTip now supports human-readable text
<img width="371" alt="SCR-20240516-nxec" src="https://github.com/HHS/OPRE-OPS/assets/4629398/56a7e68e-c554-442c-aa3d-23d2824d89db">

**Comment by fpigeonjr** [comment]
- all users `AgreementChangeRequestAlert` is now supported with changeRequests
- submitter success `Alert` is added sans the changeRequests
  - could not get the changeRequests to sync so moving on for now

**Comment by fpigeonjr** [comment]
- added logic for batched PATCH requests for budget-lines if there is an error. Tested with the `simulatedError` param
- added more tests
- fixed bug with AgreementSummary cards not staying in sync with DRAFT BLI edits

**Comment by fpigeonjr** [comment]
- adds IN_REVIEW tags and ToolTips to ALLBLIRow

**Comment by fpigeonjr** [comment]
blocked by #2375

**Comment by jonnalley** [comment]
5/31
