### ISSUE TITLE
update Figma designs to incorporate date-picker component

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2202]
- this effects the `needByDate` memorable date in the Budget Lines Form
- migrate from [memorable date](https://designsystem.digital.gov/components/memorable-date/) to[ date picker](https://designsystem.digital.gov/components/date-picker/)

**Comment by fpigeonjr** [comment]
Think I saw this incorporated into the Figma but will defer to @kimschulke and @andressacurvelo

**Comment by kimschulke** [comment]
Andressa updated Figma with the new date picker last week or the week before... I will just run through it again to make sure we didn't miss anything
