### ISSUE TITLE
Make sure onboarding doc is ready to be used

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#223]
To help us prepare for new teammates, review our [onboarding doc](https://docs.google.com/document/d/1dTe12ZsUzAHjrXwCehRdckPMOnPe66S-kHDLT6Hu3ik/edit) and clean up / update as needed.

**Comment by ninamak** [comment]
@juliaklindpaintner After your pass, I updated the Project History section and the links.  Is there anything else, or is this ready to close out once you've had a chance to review?

**Comment by juliaklindpaintner** [comment]
Thanks @ninamak! There are some outstanding comments, but I looked through your edits (thank you!) and I think we can close this.
