### ISSUE TITLE
Lock down procurement shop for now in the frontend

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2283]
### Goals
* Prevent any confusion or problematic data entry temporarily until other stories/backlog items are completed around procurement shop fees and when and how they're changed. 
* Ideally make this restriction as easy to reverse as possible, i.e. feature flag

### Tasks
- [x] Insure GCS is the default on new contracts
- [x] Disable the combo box or any other ability for a user to edit or change the procurement shop during or after the contract is created.

### Additional Context
* The impetus was conversation in a meeting with OPRE and understanding more about procurement shop changes and impacts to fee rates and a mounts over a contract's and BL's lifecycle and how that interacts with current OPS functionality. See related items:

### Resources
* #2079
* #2167
* #2139
* #1473

**Comment by maiyerlee** [comment]
Adding task: Default Agreement Type to "Contract"
