### ISSUE TITLE
See pending edits for review/approval (DD)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2307]
### User Story
As an authorized approver, I want to see all requests requiring my review for potential approval so that I can take appropriate action and the procurement process won't be further held up waiting for my input. 

### Preconditions
* #2193 is done
* One or more agreement exist with draft budget lines requested to move to planned status
* One or more agreement exist with planned budget lines requested to move to executing status
* One or more agreements exist with a submitted budget change that requires approval

### Acceptance Criteria
- [x] User can concisely see all requested changes that the user is empowered and able to review & approve.
- [x] For each change submitted (same condition for the below AC), the user can discern the type of change being requested
- [x] User can see the date the request was submitted
- [x] User can see the agreement name the request comes from
- [x] User can see the BL ID of the BL a change was requested on
- [x] User can discern the attribute(s) or property of the BL a change was requested on
- [x] User can see the original value and what the submitter has requested the attribute's value be change to (before and after) 

-----------------------------------------

#### UX
see figma links below

##### FrontEnd

- [X] #2412
- [X] Review list
- [x] #2441
- [x] add status change cards
- [x] #2459
- [x] add e2e test for change requests

##### BackEnd
- [x] #2370
  - add change_request.managing_division_id
  - find and set when CR created
- [x] endpoints, queries to find my change requests to review/approve
   - the essential for this ticket is done, find CRs for me to review for DDs and DDDs, but we may want more query options later 

### Definition of Done Checklist
- [x] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] New design/tech debt documented (if applicable)
- [ ] Build process updated
- [ ] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* [Figma dev-ready frame](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=10483-27101&t=TE4Cg8wtka953yxB-4).  The Figma link is in a frame for editing a BL's amount but this story could and should also apply for a BL status change well or potentially agreement metadata change (even though we're punting on that for now actually)
* #1964
* A more-narrative document outlining potential scenarios and needs being addressed is [here](https://docs.google.com/document/d/1KIx2aFfZ9xvR_IgNNRtd-kOPtZk1_xxzkTP98-2aUSM/edit)
* [FigJam process visual](https://www.figma.com/file/ZclJ07uGZKS4pTwM006kg8/OPS-Diagrams?type=whiteboard&node-id=562-9038&t=3WZSkvmFRX8b2AU6-4)

**Comment by fpigeonjr** [comment]
:mag: I have a suspicion that these dev tasks are out-of-scope for this user-story:
- Approve/Decline alerts for the approver (on review list page)
- Review Agreement page for the one change
  - review edit accordion
  - table diffs
- Alerts (approved/declined) on the Agreement details page

**Comment by fpigeonjr** [comment]
approve/decline dev tasks were removed based on 2358/2349

**Comment by fpigeonjr** [comment]
UX Review completed today and my take-away was to allow flexibility in the terms layout in the `ReviewCard`

**Comment by fpigeonjr** [comment]
added new FE tasks for migrating api calls to new change requests for BLI status changes

**Comment by jonnalley** [comment]
6/20
