### ISSUE TITLE
Approve/decline a change at the card level/view

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2348]
### User Story
As an authorized approver, I want to quickly and at-a-glance review and make a decision on requested changes so that the procurement process can proceed further and not have changes waiting for a decision to be made.

### Preconditions
* One or more agreement exist with `draft` budget lines requested to move to `planned` status
* One or more agreement exist with `planned` budget lines requested to move to `executing` status
* One or more agreements exist with a submitted budget change that requires approval
* #2307 is done

### Acceptance Criteria

- [x] User can directly approve the requested change (status or financial) in which case the BL's changes would occur and persist with appropriate history/event logging.
- [x] User can decline the change
- [x] After either approval or declining, the approver receives an acknowledgment of the choice and action taken
- [x] Relevant entries should be recorded in the event/history table(s) of who approved what and when and this event should be properly rendered in the history of changes to the agreement.

-----------------------------------------

#### Dev

- [x] review openapi spec for change requests

#### FrontEnd

- [x] add approve api endpoint and method
- [x] add decline api endpoint and method
- [x] add Confirmation Modals and Alerts for approver (Approve/Decline)
- [x] ensure logs are made on Agreement history
- [x] update unit and e2e tests

##### BackEnd

- [x] endpoint to approve/reject a change request
- [x] #2378

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [x] New design/tech debt documented (if applicable)
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources
* A more-narrative document outlining potential scenarios and needs being addressed is [here](https://docs.google.com/document/d/1KIx2aFfZ9xvR_IgNNRtd-kOPtZk1_xxzkTP98-2aUSM/edit)
* [FigJam process visual](https://www.figma.com/file/ZclJ07uGZKS4pTwM006kg8/OPS-Diagrams?type=whiteboard&node-id=562-9038&t=3WZSkvmFRX8b2AU6-4) 
* [Figma dev-ready frame for financial change](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=9297-51085&t=XbeU8GUcrmHPAsNV-4)
* [Figma dev-ready frame for draft-to-planned](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=6620-18218&t=I6YizAEuoB4YdGEL-4)
* [Figma dev-ready frame for planned-to-executing](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=7138-92198&t=VT8mq8xilmE8j8w2-4)

**Comment by fpigeonjr** [comment]
content changes to agreement log is #2495

**Comment by jonnalley** [comment]
7/1
