### ISSUE TITLE
Approve/decline a change when reviewing a single agreement

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2349]
### User Story
As an authorized approver, I want to review and make a decision on requested change(s) to budget lines on a single agreement so that the procurement process can proceed further 

### Preconditions
* One or more agreement exist with `draft` budget lines requested to move to `planned` status
* One or more agreement exist with `planned` budget lines requested to move to `executing` status
* One or more agreement exist with a submitted budget change that requires approval
* #2307 is done

### Acceptance Criteria

- [x] User can quickly access full agreement's details and can then review all aspects of the agreement
- [x] User can approve the requested change (status or financial) in which case the requested individual changes would occur and persist with appropriate history/event logging.
- [x] User can decline each requested change
- [x] Regardless of the choice made, the approver receives an acknowledgment of the choice and action taken
- [x] Relevant entries should be recorded in the event/history table(s) of who approved what and when and this event should be properly rendered in the history of changes to the agreement.
- [x] User can elect to do neither and back out of the review and decision process. 

-----------------------------------------

#### FrontEnd

- [x] filter by Change Requests (CR) type
  - [x] Budget Change
  - [x] Status Change
    - [x] Draft to Planned
    - [x] Planned to Executing
- [x] Review Changes Accordion
- [x] Condensed Review Card variation
- [x] #2097 
- [x] batch api calls to approve CRs endpoint
  - send along Reviewers Notes
- [x] confirmation modal and alert
  - [x] Cancel
  - [x] Approve
  - [x] Decline
- [x] toggle after approval updates to show current status vs proposed
  - [x] show diffs in table
  - [x] summary cards
  - [x] #2630
- [x] add Review Document Accordion for Status Changes to Executing
- [x] Remove the Review Changes Accordion
- [x] replace any workflow bits and api calls
- [x] add/update unit/e2e tests

##### BackEnd

- see also #2348 
  - [x] endpoint to approve/reject a change request
  - [x] #2378

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] New design/tech debt documented (if applicable)
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* This may just be as easy as linking to existing approval pages from where the user is at on #2307 ??
* A more-narrative document outlining potential scenarios and needs being addressed is [here](https://docs.google.com/document/d/1KIx2aFfZ9xvR_IgNNRtd-kOPtZk1_xxzkTP98-2aUSM/edit)
* [FigJam process visual](https://www.figma.com/file/ZclJ07uGZKS4pTwM006kg8/OPS-Diagrams?type=whiteboard&node-id=562-9038&t=3WZSkvmFRX8b2AU6-4) 
* [Figma dev-ready frame for financial change](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=9297-51085&t=XbeU8GUcrmHPAsNV-4)
* [Figma dev-ready frame for draft-to-planned](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=6620-18218&t=I6YizAEuoB4YdGEL-4)
* [Figma dev-ready frame for planned-to-executing](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=7138-92198&t=VT8mq8xilmE8j8w2-4)

**Comment by fpigeonjr** [comment]
@jonnalley once PR2625 is merged in, I don't believe there are any more dev tasks for this user-story

**Comment by jonnalley** [comment]
8/4
