### ISSUE TITLE
Cannot log into AMS/OPS in a different browser window

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#2377]
## Expected Behavior

After logging into OPS via HHS AMS, if I then logout, close and open a new browser window, I should be able to log in again.

## Current Behavior

When I try the above, I get an error message from HHS AMS:

Example Error URL: https://postprod.ams.hhs.gov/oam/CredCollectServlet/X509?bmctx=C98ACAB5AF95ECF0F8116321F664B850&miscCookies=Secure&OverrideRetryLimit=1&max_authn_level=4&ssoCookie=Secure&challenge_url=%2Foam%2FCredCollectServlet%2FX509&request_id=-7234868392553567923&authn_try_count=0&locale=en_US&resource_url=https%253A%252F%252Fpostprod.ams.hhs.gov%252FamsLogin%252FAuthRedirect%252FX509%253FTARGET%253D%252525252Foamfed%252525252Fidp%252525252Fsamlv20%252525253FstateChange%252525253Dtrue

![image](https://github.com/HHS/OPRE-OPS/assets/1972158/9837cd8b-347d-40a1-89d5-388367770790)

This issue persists for about 24 hours or so (same error message as above) and then after some time seems to allow me to login again.

## Possible Cause

- The `ops-state-key` may have changed in the second browser window.
- The HHS AMS logout functionality may be required (we are not currently logging out with AMS on OPS logout)
- There may be something we don't know about how HHS AMS works that we need to implement

**Comment by jonnalley** [comment]
@johndeange https://ams.hhs.gov/amsApp/help/docs/JobAids/activIdentity-web-based-piv-authentication-troubleshooting.html

**Comment by johndeange** [comment]
I have tried unsuccessfully to reproduce the issue for a few days.  I have been able to login to OPS locally, AMS postprod and prod without issue for at least a few days.  Closing the issue for now.
