### ISSUE TITLE
UX Figma dev page review and component ideation

### ISSUE THREAD

**Issue by npage123** [HHS/OPRE-OPS#2397]
### Goals
* Figma dev page review and component ideation

### Tasks
- [x] Review devs page in Figma to ensure all designs ready for dev are available
- [x] Ideate on what UI elements would be best suited to be components to save time when creating new designs and updating old

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by jonnalley** [comment]
6/19
