### ISSUE TITLE
API is using HTTP status codes 401 and 403 incorrectly

### ISSUE THREAD

**Issue by stevtek** [HHS/OPRE-OPS#2457]
I think 401 and 403 have been mixed up and we just need to swap them.

401: Unauthorized - although the HTTP status is called Unauthorized, it means Unauthenticated - not logged in (or no valid session)
403: Forbidden should be used for Authorization failures of a logged in user.

These are set in the error_handlers.py, but we'll need to change or check using of the numbers in tests and the FrontEnd.

**Comment by fpigeonjr** [comment]
@Santi-3rd is ok to close this ticket?

**Comment by jonnalley** [comment]
9/11

**Comment by fpigeonjr** [comment]
@rajohnson90 found more mismatches on #2852 so re-opening
