### ISSUE TITLE
View a single CAN's details

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2542]
### User Story
As an OPRE staff member, I need to see the full details of a CAN so that I can make  planning decisions and have awareness of our funding and budget.

### Acceptance Criteria
- [x] User is able to view metadata and higher-level attributes of a given CAN

-----------------------------------------

#### UX
- [x]  Explore design options for viewing a CAN (including any data viz)
- [x]  Share designs with devs for feedback
- [x]  Share designs with OPRE for feedback
- [x]  Refine design based on feedback
- [x]  Annotate designs and move to Ready for Dev

#### Dev
- [x] setup routes and tabs
- [x] add layout and CAN data
- [x] add placeholder for History
- [x] add FY dropdown

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] Usability validated (UX team)
- [X] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] New design/tech debt documented (if applicable)
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_
* [Figma Link](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=11967-82685&m=dev)

**Comment by fpigeonjr** [comment]
Routes and Tabs ![Image](https://github.com/user-attachments/assets/30a4329a-b58f-4645-b4d4-c0cc21274977)

**Comment by fpigeonjr** [comment]
@jonnalley all dev tasks are complete

**Comment by jonnalley** [comment]
11/5
