### ISSUE TITLE
Prep for ORR demo

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2669]
### Goals
* Have script and outline prepared for ORR demo and talkthrough

### Tasks
* Outline
* Solicit feedback and refine
* Decide what demo will cover
* Draft up demo script
* Rehearse demo

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by kimschulke** [comment]
Drafting an outline here: https://docs.google.com/document/d/1_P4o623rMBWhlgIckLlfxKdMVpb7_jkk00ycpo-mVus/edit

**Comment by jonnalley** [comment]
8/22
