### ISSUE TITLE
View a CAN's Funding info

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2673]
### User Story
As an OPS user, I want to understand details about the funding of a given CAN so that I can continue to manage the funds in the CAN optimally.

### Acceptance Criteria
- [x] User can view the various funding-related attributes of a CAN. Some details will change by fiscal year and so by default, the fiscal year used should be the current one. 
- [x] The user can visually discern the CAN's funds in this FY that have been received vs. un-received but still expected. 
- [x] The user can visually discern the CAN"s budget broken down by FY and differentiated among the different FY.
- [x] The user can view a listing of funding events that have occurred for the CAN for the fiscal year-to-date
- [x]  The user can select from a list of other fiscal years to update the information mentioned above that is rendered.

-----------------------------------------

#### UX
Much of the research and design done in #2542

#### Dev
- [x] #3080
  - CAN Funding Information
  - Funding Received YTD
  - CAN Budget By FY
- [x] #3081
- [x] #3110
- [x] #3179

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
<del>- [ ] New design/tech debt documented (if applicable)
<del>- [ ] Build process updated
<del>- [ ] Documentation updated or added
<del>- [ ] Feature flags/toggles created

### Additional Context & Resources
* https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=12012-119868&t=Wh3VGLVZR9M0PpPx-4

**Comment by fpigeonjr** [comment]
@jonnalley dev tasks are complete
