### ISSUE TITLE
Change Validation on Agreement Filters

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2706]
### Goals
- Change the validation on agreement filters for procurement shop
- right now, when a user clicks on the filters from the agreement list page, the UI is displaying a red error state on the procurement shop. For a better UX, we want to change the validation so it does not display an error by default, but only if/when the user tries to change the procurement shop from GCS to something else.

### Tasks
- [ ] change the validation on the filters so its not an error by default, only show an error if the user tries to change the procurement shop from GCS to something else

### Additional Context
* see screenshots below

**Comment by kimschulke** [comment]
this is what the filters look like when the user opens the filter options
<img width="460" alt="Screenshot 2024-08-20 at 10 13 45 AM" src="https://github.com/user-attachments/assets/fec09567-2507-4f20-91f8-4e23294e5167">

**Comment by kimschulke** [comment]
I'm actually not sure if we need any validation at all here. We can just default to All and the agreements will only have GCS because we validate that at the create-agreement-level. If the user tries to filter by another procurement shop, they can do it, but there will be no results because all agreements will be using GCS.... thoughts?

**Comment by fpigeonjr** [comment]
Think our test data may have other-than-GCS procurement shops but will need to check. May be easier to just default to GCS and if user changes, than run validation checks.

**Comment by fpigeonjr** [comment]
> I'm actually not sure if we need any validation at all here.

Yes I agree.

**Comment by fpigeonjr** [comment]
- UX Review on 8/27/24

**Comment by jonnalley** [comment]
8/27
