### ISSUE TITLE
Login pause/delay

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#2760]
## Expected Behavior

After I login, the browser should quickly bring me to the homepage.

## Current Behavior

There is a long pause on the log in screen (up to 5s) before I am redirected to the homepage.

## Steps to Reproduce

1.
2.
3.
4.

## Possible Implementation

Capture some timing metrics to see where the bottleneck is.

**Comment by jonnalley** [comment]
@johndeange this seems like a dupe of #2743

**Comment by jonnalley** [comment]
hearing no objection to the dupe claim, closing.
