### ISSUE TITLE
Mismatching validation errors

### ISSUE THREAD

**Issue by npage123** [HHS/OPRE-OPS#2770]
I created an agreement and only added a name. When presented with validation errors after creation, I went in to edit the agreement to fix them. It appears that the errors on the view agreement page don't match up with the errors on the edit agreement page. Some missing and one isn't flagged as an error as it was on the view agreement page.

![Image](https://github.com/user-attachments/assets/a492ace5-0057-45e2-9472-7680077d1b0a)

**Comment by fpigeonjr** [comment]
- Contract Type missing validation in review page

**Comment by npage123** [comment]
Reviewed with Frank and all looks good and fixed!
