### ISSUE TITLE
BE unit tests fail if run at night

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#2784]
The BE unit tests fail if run at night.  Attached error log.

Possible cause:

Check out `test_agreement_history_log_items` and `test_agreement_history_log_items_with_change_requests` - they compare dates without timezones

[error.log](https://github.com/user-attachments/files/16979899/error.log)

**Comment by jonnalley** [comment]
Very clever discovery

**Comment by jonnalley** [comment]
9/16
