### ISSUE TITLE
Complete CAN wireframe user research

### ISSUE THREAD

**Issue by stvnrlly** [HHS/OPRE-OPS#284]
### Goals
[Research plan](https://docs.google.com/document/d/1RrPyT2OUeWQzbxtbGbzQFc4jKU5EEV0irCwRVreAdFY/edit?pli=1#heading=h.i1qdr162pygc)

### Tasks
- [x] Transfer documents from 18F to Flexion
- [x] Complete user feedback sessions
- [x] Synthesize findings

### Additional Context
This research will inform future iterations of the CANs wireframes. What we learn from users will be directly translated into design and content improvements to ensure this functionality meets user needs and is easy to understand.

### Resources
* [Notes](https://docs.google.com/document/d/1hJSYih_HGx_Lcwfn0BC7UnsqgKFed1uql1BEHu8KfM4/edit#heading=h.i1qdr162pygc)

**Comment by kimschulke** [comment]
Two remaining interviews scheduled for July 5 at 10am and 10:30am est

**Comment by kimschulke** [comment]
Here is the Mural board which shows synthesis of our interview notes across all 6 users and a summary of findings to inform future iterations of the CANs wireframes

https://app.mural.co/t/flexion6734/m/flexion6734/1656610435704/a74bab9335d057719abcb79e67e0a4bca7fb2cc1?sender=kschulke5503

**Comment by jonnalley** [comment]
@kimschulke If all the tasks are really done, I'd say it's safe to close.
