### ISSUE TITLE
CAN summary info

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2842]
### User Story
As an OPS user, I want to know summary or aggregate information about all the CANs in the list I'm accessing.

### Preconditions:
* Sufficient CANs are available and loaded int he database.
* #346 is done

### Acceptance Criteria
- [x] User can view and discern the total budget amount for all CANs in the returned list
- [x] This budget amount should be broken down by new funding in the selected FY and "carry-forward" money and the user can discern the ratio between those two groupings.
- [x]  User can discern the spent vs. available amounts for the total budget amount in the currently selected FY  mentioned in previous AC.
- [x]  There's no particular role restriction on viewing this data

-----------------------------------------

##### Backend
- [x] #2961
- [x] #2962
  - fiscal year and more than one CAN
  - query params for filters 
- [x] #3162

##### FE
- [x] Calculate FY Budget and Remaining for all CANs
- implement summary cards (may already have components)
  - [x] #2971
  - [x] #2972
  - [x] add api calls to get data for cards
  - [x] adds unit/e2e tests

##### CAN List tasks
- [x] portfolio filter
- [x] fiscal_year_budget filter
- [x] reset filter
- [x] CANs Total Budget Card currency formatting and layout

##### CAN Spending Tab

- [x] Agreements are hard-coded in left Card
- [x] Draft budge lines are hard-coded in Right Card
- [x] Agreement Name in Table 
- [x] Procurement Shop in Table

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] Usability validated (UX team)
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
<del>- [ ] New design/tech debt documented (if applicable)
<del>- [ ] Build process updated
<del>- [ ] Documentation updated or added
<del>- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by fpigeonjr** [comment]
https://github.com/HHS/OPRE-OPS/issues/346#issuecomment-2364109569

**Comment by fpigeonjr** [comment]
@jonnalley dev tasks are complete
