### ISSUE TITLE
Brief Flexion on OCIO's data migration work

### ISSUE THREAD

**Issue by stvnrlly** [HHS/OPRE-OPS#285]
### Goals
* Get Flexion up to speed on what/why/how the MAPS database is being replicated

### Tasks
- [x] 18F gives Flexion the scoop
- [x] Attend Wednesday's OCIO meeting about this very thing

### Resources
* Relevant [wiki pages](https://github.com/HHS/OPRE-OPS/wiki/08-Technical-documents)

**Comment by stvnrlly** [comment]
Tim, Peter, and Jonathan will share this responsibility depending on availability

**Comment by jonnalley** [comment]
multiple conversations held last week on this. I feel this has been completed at this time.
