### ISSUE TITLE
Discuss GitHub Repo "Settings" with OCIO Team

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#294]
### Goals
* Ensure proper Branch Protections, Repo Settings, etc are configured correctly. In addition, if any additional GitHub Policy / Teams need to be created to modify edit GH Secrets or Actions

### Tasks
- [x] Schedule a meeting with Domenic Caruano to discuss Repo Settings

### Additional Context
* Discuss with Domenic Caruano (Domenic.Caruano@hhs.gov) about the

**Comment by halprin** [comment]
We were added to the HHS organization and were able to make teams and give those teams access.
