### ISSUE TITLE
add values to CAN (Funding Received, Funding Method, and Funding Type)

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#3110]
[Visual to derivations](https://lucid.app/lucidspark/601d8f63-4ee4-4c0b-b020-55581ea0cb7a/edit?viewport_loc=-28%2C-187%2C2659%2C1320%2C0_0&invitationId=inv_8c620359-ca47-4da4-85a9-0b754d0563a5)

**Comment by maiyerlee** [comment]
Completed by PR https://github.com/HHS/OPRE-OPS/pull/3120
