### ISSUE TITLE
Update Roles

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#3111]
### Goals

Update the User Roles in OPS to follow the new requirements. OPS should allow for the following User Roles: System Owner, User Admin, Budget Team, Procurement Team, Reviewer/Approver, Viewer/Editor

### Additional Context & Resources

* admin == System Owner
* user == Viewer/Editor
* division-director == Reviewer/Approver
* Roles Google Doc: https://docs.google.com/document/d/1App45I71HymOgmVCzxnrOnPQBW0CZb4sTQouB5fuaLU/edit?tab=t.0

**Comment by jonnalley** [comment]
12/5
