### ISSUE TITLE
Story: Filter List of CANs

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#347]
### User Story
As a budget team member, I want to filter the list of all CANs to find one or more specific CANs easily.

### Acceptance Criteria
- [x] User can filter a listing of CANs by by the active period(s), Method(s) of Transfer, Portfolio(s), and FY budget range
- [x] Within a given criteria, multiple options are evaluated using boolean OR logic (ex. 1 year or 2 year active period)
- [x] The combination of the above criteria are cumulative/additive filters (boolean AND)
- [x] After a filter is applied, any and all applied filters are shown to the user so that the user is aware of what filters are limiting the CANs being returned to them.
- [x] A given filter criteria can then be individually removed.
- [x] The user can also choose to reset and clear all of the above filtering/criteria in one interaction.
- [x] User can choose one and only one fiscal year to filter the list of CANs by. The selection of this FY would persist across all tabs the user chooses for this page. Additionally, any selection of fiscal year would be additive and supplementary to the filters chosen above.
- [x] By default, the fiscal year selected and thusly filtered would be the current fiscal year based on the current date.

-----------------------------------------

#### UX

- Design is done in #346

#### Dev

- [x] #2868
- [x] #2878
- [x] #2888
- [x] #2892
- [x] #2901
- [x] #2907
- [x] #2910
- [x] #2909
- [x] Clear Filters

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] New design/tech debt documented (if applicable)
- [-] Build process updated
- [-] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources
- [react-range-slider](https://github.com/n3r4zzurr0/range-slider-input)
- [uswds-range-slider](https://designsystem.digital.gov/components/range-slider/)
- [Slider Design article](https://www.nngroup.com/articles/gui-slider-controls/)

**Comment by fpigeonjr** [comment]
UX Review on 10/22/2024
- [ ] always show TBD amounts
- [ ] not show the Budget filters if user has not interacted with it

**Comment by fpigeonjr** [comment]
@jonnalley all sub-tasks are complete for this story
