### ISSUE TITLE
Create Research Plan for Portfolios

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#349]
**Goals**
Create a research plan to understand user needs related to viewing a portfolio. This research will inform design options for viewing a portfolio which will be tracked in a separate user story.

**Tasks**

- [x] Draft research plan including goals, methods, questions
- [x] Share research plan with team for feedback

**Comment by kimschulke** [comment]
Draft research plan here: https://docs.google.com/document/d/1EaEliLK8o9UORCcopjXQxCvlvUB9rmBOvcDZHUQ76Tk/edit
