### ISSUE TITLE
Update the OCIO org chart

### ISSUE THREAD

**Issue by carjug** [HHS/OPRE-OPS#40]

**Comment by alexsoble** [comment]
👋 Just noting that if the eng team runs out of work or is blocked while I'm OOO and wants to pick up more cards, this could be a great one! 

Would be super helpful to get more info on the OCIO org chart // structure. One idea would be to ask for an official OCIO org chart; we could start by asking Randeep.

**Comment by ninamak** [comment]
Alex updated the chart.  Would be worth picking back up once we start the ATO process and see what additional details we can get, possibly ask for their org chart, etc.
