### ISSUE TITLE
Story: User Log In / Out

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#447]
### User Story
As an OPRE staff member, I want to log in and log out of OPS so that authentication can occur and be used later for authorization.

### Acceptance Criteria
- [x] A user can "log in" with a previously-created user account using some authentication scheme. Authorization is binary--no further verification or pre-authorization is required for this story.
- [x] User should be able to manually "log out" and have their logged in state cleared upon demand

-----------------------------------------

#### Dev:
- [x] Explore OIDC-React - @johndeange 
- [x] Explore Authlib - @xlorepdarkhelm 
- [x] Codify drawing of login flow - @halprin 
- [x] Create backend endpoint to receive OIDC AuthN token and spit OPS-specific JWT and user ID back - @halprin and @xlorepdarkhelm
- [x] Define what authentication scheme(s) will be used
- [x] #1395
- [x] Define concepts around session state and how that will be achieved. Hash out pseudo-options for log in @tdonaworth 
- [x] Build backend code "scaffolding" around log in state.  @tdonaworth 
- [x] Add custom "User" object @tdonaworth and @johndeange 
- [x] Add cypress e2e tests for login - @johndeange 
- [x] Add backend unit tests - @tdonaworth and @xlorepdarkhelm 
- [x] Create frontend code/UX related to the log out interaction
- [x] #1171 @xlorepdarkhelm
- [x] Create ADRs based on research and experiments - @tdonaworth 
- [x] Change JWT private key and securely transmit secret - @halprin 
- [x] User authenticates through OIDC into OPS.
- [x] System does a check to see if that user already exists (to get user details)
- [x] If the user doesn't, create a user. 

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests passed
- [ ] Automated integration tests passed
- [ ] Automated quality tests passed
- [ ] Automated load tests passed
- [ ] Automated a11y tests passed
- [ ] Automated security tests passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* Logging/auditing of log in/log out events is not covered in this story nor even this epic. 
* #443

**Comment by halprin** [comment]
After discussing a bit more about the Login.gov flow, we created a [Lucidchart diagram](https://lucid.app/lucidchart/d36f95e3-7e29-4182-95ea-f7829d777470/edit) outline our thoughts.

**Comment by halprin** [comment]
This [Real Python article](https://realpython.com/flask-google-login/) was helpful in explaining how to interact with an OIDC provider.  The things outlined in the article differ from what we're planning on doing since we will be combining a frontend and backend approach.

**Comment by halprin** [comment]
Two Python libraries to handle the OIDC interaction are...
- [oauthlib](https://pypi.org/project/oauthlib/)
- [Authlib](https://docs.authlib.org/en/latest/client/django.html)

**Comment by halprin** [comment]
We have a [backend draft PR](https://github.com/HHS/OPRE-OPS/pull/452) that is for viewing our work in progress.  We have a backend endpoint that will call the OIDC provider and a library to do this interaction, but nothing work.  The main file to look at is `oidc.py`.

**Comment by jonnalley** [comment]
The more-working solutions to the remaining tasks have been implemented in the Flask refactor

**Comment by jonnalley** [comment]
10/9
