### ISSUE TITLE
View Portfolio Details: Total FY Funding 

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#459]
### User Story
As an OPRE staff member, I want to view total fiscal year funding for each portfolio, so that I know how much money we have in our budget.

### Preconditions:
* We can presume that the current fiscal year is all that needs to be handled for the time being.
* A portfolio exists and has associated funding in the backend
* A system user cannot alter or update funding via the app

### Acceptance Criteria
- [x] User can view the total fiscal year funding for a chosen portfolio, formatted in US dollars.

-----------------------------------------

#### UX:
- [x] Finalize language on "current" vs. "total"
- [x] Create design and upload design files for development

#### Dev:
- [x] Build portfolio details shell page in React
- [x] Create backend endpoint to calculate total funding, as opposed to frontend
- [x] Create any database structure not already present
- [x] Add new e2e tests - @johndeange 
- [x] Add new a11y tests - @johndeange 
- [x] Ideally and if feasible, acquire actual and point-in-time financial data aggregated up for each portfolio, ~if not already received back on 8/23 or 8/25 (zip)~

### Definition of Done Checklist
~~- [ ] Usability validated~~
~~- [ ] UI works as designed~~
~~- [ ] OESA: Code refactored for clarity~~
~~- [ ] OESA: Dependency rules followed~~
- [x] Automated unit tests passed
- [x] Automated integration tests passed
~~- [ ] Automated quality tests passed~~
~~- [ ] Automated load tests passed~~
- [x] Automated a11y tests passed
~~- [ ] Automated security tests passed~~
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
~~- [ ] Design/tech debt eliminated~~
~~- [ ] Build process updated~~
~~- [ ] Documentation updated or added~~
~~- [ ] Feature flags/toggles created~~

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by johndeange** [comment]
https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/Portfolios-2?node-id=144%3A5515

**Comment by kimschulke** [comment]
Attached mockup for the component we are building

[Screen Shot 2022-09-28 at 3.55.40 PM.png](https://images.zenhubusercontent.com/5f34386b28244c7b7db90198/f2a909e7-e8ac-458d-96d5-0fc13aa87dfc)

**Comment by kimschulke** [comment]
Total FY Funding = Sum of all CANs allocated to each portfolio. It's the starting total for the FY without accounting for whats been planned, obligated or remaining.

**Comment by jonnalley** [comment]
Point-in-time financial data aggregated up for each portfolio is not feasible as portfolios do not exist in the systems of record
