### ISSUE TITLE
View Portfolio Budget Summary

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#460]
### User Story
As an OPRE budget officer, I want to understand the breakdown of a portfolio's funding so that I'm able to better manage budgets.

### Preconditions
The current fiscal year is all that needs to be handled for the time being.

### Acceptance Criteria
- [x] User should be able to see the total dollar amount of planned funds of a portfolio
- [x] User should be able to see the total dollar amount of obligated funds of a portfolio
- [x] User should be able to see the total dollar amount of "in execution" funds of a portfolio
- [x] User should be able to see the total dollar amount of remaining (unobligated) funds of a portfolio
- [x] User should be able to see "at a glance" and discern the ratio of obligated to un-obligated portfolio funds

-----------------------------------------

#### UX:
- [x] Get clarification and definition of the terms from OPRE (planned, obligated, remaining)(Determine how these items will be calculated)
- [x] Determine best order of information (planned, obligated, and then remaining)
- [x] Determine best language/phrasing for the components involved
- [x] Determine interactions for the graph (tooltip?)
- [x] Create design assets and provide design file to Dev

#### Dev:
- [x] Build frontend components needed to meet AC @johndeange 
- [x] Build backend components needed to distinguish between the different classification of funds @johndeange @xlorepdarkhelm 
- ~~[ ] Update CD to use new cloud.gov environment~~ #503 
- [x] Decide on libraries to build graphs @johndeange 
- [x] Add new unit tests @tdonaworth 
- [x] Add more unit tests @johndeange 
- [x] Add new e2e tests @tdonaworth 
- [x] Add new a11y tests

### Definition of Done Checklist
- [x] Usability validated - UAT to come when entire page is more complete
- ~~[ ] UI works as designed~~
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests passed
- [x] Automated integration tests passed
- [x] Automated quality tests passed
- [ ] Automated load tests passed
- [x] Automated a11y tests passed
- [x] Automated security tests passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
-  ~~[ ] Design/tech debt eliminated~~
- ~~[ ] Build process updated~~
- ~~[ ] Documentation updated or added~~
- ~~[ ] Feature flags/toggles created~~

### Additional Context & Resources
* Remaining funds would be the sum after planned and obligated funds are subtracted from the total
* Maybe cents can be shown in smaller text size?

**Comment by kimschulke** [comment]
Some questions for further exploration ---
- Does "obligated" funding mean there is an associated agreement (contract, grant, IAA)? What makes funding "obligated"?
- How do we determine "planned" funding? What makes funding "planned"?
- Does "remaining" imply anything left over from the starting FY total after obligated and planned?

**Comment by jonnalley** [comment]
@kimschulke Per Camille back on 7/28: 

> "OPRE's money in legislation gets determined as 1 year money, 2 year money, etc... Once it's in OPRE's bank account, we have to obligate that money....If OPRE doesn’t de-obligate money by 9/30 on the year it expires, the money is no long usable. Not all CANs have multi-year money that have to be obligated."

Because of what agreements are, obligated funding would necessarily and categorically have to be on an agreement.
 
The meeting recording back on 7/28 is helpful for this. Sadly and much to my surprise, it doesn't seem that we asked your latter question of what actual process makes funding obligated.

**Comment by kimschulke** [comment]
working on a mini research plan to help us further clarify planned, obligated and remaining -- where this data comes from, how it's calculated, etc

**Comment by kimschulke** [comment]
Document where we are **drafting** out current understanding --- https://docs.google.com/document/d/1nQBIYUg3cjLkC0LA_8P82LvpU0wSmTqZQSypZvmS3GE/edit

**Comment by kimschulke** [comment]
As discussed on 10/11, we will be adding an additional funding status for "In Execution"

Updated wireframes to follow

**Comment by kimschulke** [comment]
Wireframes:

<img width="551" alt="Screen Shot 2022-10-11 at 3 22 11 PM" src="https://user-images.githubusercontent.com/65555918/195180559-563aaf16-d744-4362-867f-5d58719fd325.png">

Link to Figma: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=215%3A5313

**Comment by kimschulke** [comment]
On hover, piece of pie zooms slightly bigger than the other pieces. Annotated graph text (Obligated: 56%) updates to provide % on whatever piece is being hi-lighted.

**Comment by kimschulke** [comment]
Color palette for data visualizations to follow shortly

**Comment by kimschulke** [comment]
Heres what the interaction looks like - on hover each slice gets slightly bigger and annotation appears on the bottom right

<img width="472" alt="Screen Shot 2022-10-12 at 1 19 50 PM" src="https://user-images.githubusercontent.com/65555918/195407862-b08792a2-00e4-4592-9ab5-e54180671893.png">

**Comment by jonnalley** [comment]
tried out victory but may prove too cumbersome. Experimenting with another

**Comment by kimschulke** [comment]
Current design for Portfolio Budget Summary here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=706%3A12865
