### ISSUE TITLE
Projects & Spending Summary Info

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#490]
### User Story
As an OPRE staff member, I want to see summary information about a portfolio's research projects so that I can assess the volume and status of work for a portfolio.

### Acceptance Criteria
- [ ] ~User can see a comparison between their research project's budget and spending with the remaining amount for the selected FY~ Deferred to #727
- [x] User can see the total number of research projects for the selected FY 
- [x] User can see the total number of admin & support projects the selected FY
portfolio
- [x] User can see the total number of agreements for the chosen portfolio for the fiscal year with their status

-----------------------------------------

#### UX
- [x] Determine instructional text
- [x] Iterate on design based on user feedback
- [x] Provide design assets to developers

#### Dev
- [x] Improve state handling in unit tests @johndeange 
- [x] Build "tabs" component(s) in React for Budget & Funding/Research Projects, etc...
- [x] Build any shell or pre-requisite components
- [x] Build frontend components needed to meet AC - @fpigeonjr 
- [x] Experiment with importing real research project data building in the relationships, etc... building a data importation pipeline - @johndeange 
- [x] Experiment with de-id'ing data - @johndeange 
- [x] Develop plan to integrate Behave and Luigi
- [x] Write and experiment with BDD tests - @johndeange 
- [x] Build other backend components (data structures, business logic, database schema, etc...) needed for research projects including name, funding, and descriptions  as they pertain to agreements, CANs, and descriptions
- [ ] Conduct brief experiment with desert/marshmallow for data marshaling.
- [x] Cleanup linters - @johndeange 
- [x] Acquire additional data needed for research projects that weren't included in the spreadsheets

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] ~~Build process updated~~
- [ ] ~~Documentation updated or added~~
- [ ] ~~Feature flags/toggles created~~

### Additional Context & Resources
* Fiscal year "spending" is aka an "outgoing agreement"
* Fiscal year "funding" is aka the income for this portfolio, or what's provided by the CANs.
* Searching/filtering and sorting projects is needed but handled in a later story
* Additional research and design needed:
  * Identify acronyms for each project and design a tooltip/hover over for full text

**Comment by jonnalley** [comment]
Initial PR done; work now on the RP description and header things

**Comment by kimschulke** [comment]
Design is ready for development! https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details?node-id=2253%3A7227&t=bbhj4sHSFEL9nhYu-1

**Comment by jonnalley** [comment]
Frontend is mostly complete but is using hardcoded data and not wired up yet

**Comment by fpigeonjr** [comment]
@kimschulke @andressacurvelo,
Ready for  design/usabity review on  [development](https://ops-dev.fr.cloud.gov/).

**Comment by kimschulke** [comment]
One thing I noticed, the amounts are not showing up as percents. It just shows 0%.

<img width="503" alt="Screenshot 2023-03-06 at 10 29 50 AM" src="https://user-images.githubusercontent.com/65555918/223176922-966401d9-1468-4e78-b0c1-6e739f8efd8c.png">

**Comment by fpigeonjr** [comment]
Great feedback @kimschulke,
We have wired up the `total_funding` which is the top amount in bold which is $0 as shown above. The remainder of the values are hard-coded and being divided by the total funding so that is why we are getting zero. 

Once we are pulling data from the backend then we'll need to refactor this component to use the real data.

**Comment by jonnalley** [comment]
@johndeange are we done with desert at least for now, if so, please do feel free to check off that and any other remaining tasks.

**Comment by jonnalley** [comment]
@johndeange are we done with desert at least for now, if so, please do feel free to check off that and any other remaining tasks.

**Comment by jonnalley** [comment]
@kimschulke @andressacurvelo I added #727 for us to address what we had to leave in that state for now for us to come back sometime post-MVP to fix that. Barring that issue, if you're pleased that the UI functions as designed, please do check that checkbox at your convenience.  cc @fpigeonjr

**Comment by kimschulke** [comment]
Looks good!

**Comment by jonnalley** [comment]
opre review on 3/9
