### ISSUE TITLE
Portfolio Budget Funding YTD

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#494]
### User Story
As an OPRE team lead or budget officer, I want to know how much of expected internal CAN funds have actually been received (funded) for a given portfolio so that I can avoid not spending or obligating funds that I do not yet have at this point in the fiscal year. 

### Preconditions
Assume that we only need to facilitate the current fiscal year for now

### Acceptance Criteria
- [x] For each internal CAN in a portfolio, the user can see how much of the expected funds have been received and are available, and how much is left to come in the fiscal year, formatted in US dollars
- [x] User can quickly ascertain the ratio of received funds for each CAN vs. funds that are still to come.

-----------------------------------------

#### UX
- [x] Explore design options for graph to show funds received vs expected
- [x] Ensure design can accommodate scenarios of differing number of CANs for a single portfolio (1 CAN vs 10 CANs)
- [x] Determine research plan
- [x] Schedule time with users @kimschulke 
- [x] Conduct feedback session with users
- [x] Iterate on design based on feedback
- [x] Provide design assets to developers

#### Dev
- [x] Create new frontend component for representing each CAN's received funding fiscal YTD @johndeange 
- [x] Create new backend logic, data structures, database schema, etc... for the concept of tracking how much of a portfolio's CAN's funding has been received in the FY. @tdonaworth @johndeange 

### Definition of Done Checklist
- ~~[ ] Usability validated~~
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [ ] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* When funds are allocated (regardless of source), OPRE doesn't always receive those funds right away or at the start of the fiscal year. Sometimes they come at various increments throughout the funding period. 
* How will the amount currently funded get updated? Does it come from FBIS or UFMS? or manually entered by the user?

**Comment by kimschulke** [comment]
3 interviews scheduled for next week (on Monday 10/31 and Wednesday 11/2). Meeting with 2 Team Leaders and 1 Budget Team Member.

**Comment by kimschulke** [comment]
Current design of Portfolio CANs here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=706%3A12865

** Please note we are still doing user research / design feedback with OPRE. Design may change depending on feedback.

**Comment by kimschulke** [comment]
Working on research feedback summary and planning to share more next week :)

**Comment by jonnalley** [comment]
Good discussion held today on what color & scheme should be used for successive CANs listed on the page. The consensus was to use the same color for multiple managed CANs on a portfolio. See sigma link in previous comments.

**Comment by jonnalley** [comment]
Initial iteration deployed to dev!
