### ISSUE TITLE
List of Projects & Additional Funding

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#497]
### User Story
As an OPRE staff member, I want to see a listing of a portfolio's research projects so that I can quickly assess and better manage the lifecycle of those research projects.

### Acceptance Criteria
The user can see the following attributes on the current portfolio:
- [x] A listing of not only Research Projects but also Administrative & Support Projects
- [x] Explanatory/instruction text about each list of projects
- [x] Project name
- [x] Currently-selected FY funding (for the entire project)
- [x] Cumulative Funding to Date (based on selected FY and the First Award Date)
- [x] First Award Date (earliest origination/start date of any agreement associated to the RP)
- [x] Number of CANs contributing to the project in the select FY
- [x] Agreement type (contract, grant, IAA, AA, Direct obligation, or mixed)

-----------------------------------------

#### UX
- [x] Finalize design changes
- [x] Research on adding a completed status for past projects or specify the graph is only showing current projects
- [x] Make determinations on what features will be postponed for later stories
- [x] Provide design assets with annotations to developers

#### Dev

- [x] Build frontend components needed to meet AC
- [x] Build backend components (data structures, business logic, database schema, etc...) needed for agreement status
- [x] Acquire actual data (i.e. methodologies and populations, see AC) to populate at least an initial portfolio's worth of research projects with
~- [ ] Acquire origination date of the research projects~
- [x] Update breadcrumbs/navigation

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] ~~Build process updated~~
- [ ] ~~Documentation updated or added~~
- [ ] ~~Feature flags/toggles created~~

### Additional Context & Resources
* This story is not the same as viewing the full details of a given RP--that's #668
* Research done in #491 will help inform this

**Comment by kimschulke** [comment]
For now, users will be able to view past projects by changing the selected FY from the dropdown. This means users will only be able to view information FY by FY, one at a time. If we find out later that they want/need to see a summary of all past projects collectively, we will create a new user story to figure out a solution for that.

**Comment by kimschulke** [comment]
design is just about ready for development. Still working on options for sorting the columns, will provide an update on that soon!

**Comment by kimschulke** [comment]
Still need to outline the annotations/interactions/requirements but here is the design -- https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details?node-id=144%3A5515&t=CI7Omi6KwsJUFXb9-1

**Comment by kimschulke** [comment]
Design is ready for development! https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details?node-id=2253%3A7227&t=bbhj4sHSFEL9nhYu-1

**Comment by jonnalley** [comment]
Frontend is mostly complete but is using hardcoded data and not wired up yet

**Comment by fpigeonjr** [comment]
@kimschulke @andressacurvelo,
Ready for design/usability review on [development](https://ops-dev.fr.cloud.gov/).

**Comment by kimschulke** [comment]
@fpigeonjr - looks good, but one question, is the hover state/blue rectangle on item selected part of the uswds component? 

<img width="752" alt="Screenshot 2023-03-06 at 11 54 38 AM" src="https://user-images.githubusercontent.com/65555918/223177896-ac80b919-a54e-4037-b51f-ec55021dbe1f.png">
<img width="576" alt="Screenshot 2023-03-06 at 11 54 44 AM" src="https://user-images.githubusercontent.com/65555918/223177907-1484d6f3-fde6-40e3-85dc-2fd6b2468db6.png">

**Comment by fpigeonjr** [comment]
Feedback from SU should be resolved in [PR723](https://github.com/HHS/OPRE-OPS/pull/723).

Also I believe the active state blue stroke on the elements is part of the [a11y considerations](https://designsystem.digital.gov/documentation/accessibility/) baked into the uswds.

**Comment by kimschulke** [comment]
Thanks @fpigeonjr !

**Comment by jonnalley** [comment]
pre review on 3/10
