### ISSUE TITLE
Carry-forward Funds Update

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#594]
### User Story
As an OPRE staff member, when looking at a portfolio and its CANs, I want to better understand how much of the funding is from the currently-selected fiscal year & how much is from prior fiscal years so that I can make better decisions about the timing of fund usage.

### Acceptance Criteria
- [ ] When viewing a portfolio's details, the user can quickly discern if a CAN has carry-forward funds.
- [ ] When viewing a portfolio's summary, the user can quickly discern and see the amount of funds new to the FY and carried forward from a fiscal prior to the selected one.
- [ ] When viewing a portfolio's details (CANs), the user can quickly get an idea for the ratio of the CAN's received funds to expected funds in the currently-selected FY.
- [ ] When viewing a portfolio's summary, the user can quickly get an idea for the ratio of funds carried forward from prior fiscal years to funds new to the fiscal year.

-----------------------------------------

#### UX
- [x] Make any adjustments/edits to the design
- [x] Provide design assets to developers

#### Dev
- [x] In the backend, build in the math necessary to sum up all the prior FYs carry-forward numbers (received and expected)
- [x] Update the PortfolioSummaryCards components
- [x] Update the CanCard

### Definition of Done Checklist
- [ ] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* Carry-forward funds have already been introduced at the overall portfolio level and possibly the CAN level on the backend. 
* 1 year CANs by definition wouldn't have any carry-forward funds.

**Comment by kimschulke** [comment]
Updated designs in Figma

**Comment by jonnalley** [comment]
Was just re-listening to the recording from 2/2 and wanted to clarify that for the PortfolioSummaryCards, that should be expected money, not just received.

**Comment by fpigeonjr** [comment]
@xlorepdarkhelm the demo today looked good.

**Comment by kimschulke** [comment]
@xlorepdarkhelm  Let me know which environment to review the design for DoD. I don't see any portfolios in dev or staging at the moment. Thank you!

**Comment by jonnalley** [comment]
pre review on 3/6
