### ISSUE TITLE
Improve layout of CAN status and amounts

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#597]
### User Story
As an OPRE staff member, when viewing a portfolio's details I want it be easier to discern the budget status for each CAN so that I can more easily create spending plans and better understand the progress of fund usage across a portfolio. 

### Acceptance Criteria
- [x] User can more-quickly see and compare CAN status across one or more CANs on a given portfolio
- [x] Static non-financial elements of a CAN's status are not mixed in logically with financial elements of CAN status.
- [x] The user should experience greater consistency between the portfolio summary and portfolio details
- [x] Percentages should be always visible to the user

-----------------------------------------

#### UX
- [x] Make any adjustments/edits to the design
- [x] Provide design assets to developers

#### Dev
- [x] Update layout to match Figma
- [x] Implement doughnut graph and legend on the CanCard
  - [x] maintain hover state between graph and legend
- [x] Update data model/structure of CANs to include `appropriation_date` 
- [x] Update line graph on the CanCard
- [x] Add/update tests

### Definition of Done Checklist
- [x] UI works as designed
- [X] OESA: Code refactored for clarity
- [X] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [ ] ~~Design/tech debt eliminated~~
- [ ] ~~Build process updated~~
- [ ] ~~Documentation updated or added~~
- [ ] ~~Feature flags/toggles created~~

**Comment by jonnalley** [comment]
We had good feedback from the PO yesterday and from the budget team earlier today on this

**Comment by kimschulke** [comment]
updated designs in Figma - thank you @andressacurvelo!

**Comment by fpigeonjr** [comment]
Is this task associated with #594?
> Update line graph on the CanCard

**Comment by jonnalley** [comment]
@fpigeonjr No, most of the heavy lifting to update the CanCard was intended to relate to this story.  The only thing on #594 that pertains to the CanCard is that "tag" or label we discussed this morning to indicated that a 5 year CAN has some carry forward monies from a prior FY

**Comment by jonnalley** [comment]
Was just re-listening to the recording from 2/2 and wanted to clarify that for the summary section, those dollars and percentages should be of the expected money, not just received.  That may already be what you're doing, but I didn't see it called out necessarily thus far and thought I should. :-)

**Comment by fpigeonjr** [comment]
@andressacurvelo @kimschulke This is ready for usability/design review.
Thanks!

**Comment by kimschulke** [comment]
Just to close the loop here - design looks great and works as intended. One minor change needed - the white font color over the grey background for the Funding Expected should be changed to black instead of white. White is not contrast compliant over the grey.

@fpigeonjr  Please change font color for ##% of Funding Expected to #1B1B1B on hover. Thank you! Other than that, looks great!

**Comment by fpigeonjr** [comment]
> @fpigeonjr Please change font color for ##% of Funding Expected to #1B1B1B on hover. Thank you! Other than that, looks great!

Thanks @kimschulke this has been resolved and deployed to  the `development` environment.
