### ISSUE TITLE
DevEx: Improve PyTest Unit Tests

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#634]
### Goals
* Have our unit tests succeed using our chosen production persistence store (PostgreSQL) against the same production dataset.

### Tasks
- [ ] Decide on how to handle this with our container approach
- [ ] Fix all unit tests to use a PostgreSQL instance (SQLAlchemy) instead of sqlite)

### Additional Context
* Currently PyTest is using a sqlite database for unit testing instead of our actual desired dataset in PostgreSQL, which is suboptimal for the desired state of unit testing.

**Comment by johndeange** [comment]
`OPS-490-pytest-docker-psql` has an example of using the `pytest-docker` plugin for spinning up a Postgres DB for use in unit testing.  The unit tests are currently failing when run against Postgres.  This approach would have to be applied in the Github Action as well to spin up a container when running unit tests.
