### ISSUE TITLE
Decide on & onboard with authn provider for OPS

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#656]
### Goals
* Have a decision reached on which authentication service provider we'll use as the go-forward solution for OPS and get onboarded to it

### Tasks
- [x] Gather info from ACF OCIO on if they have a direction or mandate on login.gov, HHS AMS, or others (OPRE Tech Lead is coordinating)
- [x] If applicable, gather HHS AMS cost and onboarding info including registration, etc...
- [x] #970
~- [ ] #1077~
~- [ ] #1078~
~- [ ] If necessary, discuss any configuration choices and factors with OPRE stakeholders and reach consensus~

### Additional Context
*

**Comment by AmareB441** [comment]
As per the suggestion OPRE Data Security Manager, an email has been sent to the ACF OCIO Deputy Cyber Security Manager for guidance on Login.gov/HHS AMS services including the request for requirement information or documentations that we should follow in the design and development process.

**Comment by jonnalley** [comment]
Following up on Amare's previous comment, it would appear the direction for the time being is to use the HHS-provided AMS. More direction and interaction with OCIO to come on this.

**Comment by jonnalley** [comment]
AMS meeting scheduled for next week, yay :-)

**Comment by jonnalley** [comment]
met with reps from ACF/OCIO to get a client added for us on their end. Right now it just points to localhost for local dev while all the various AMS options and configuration is tweaked optimally as well as changes being made to accommodate on the OPS end. Following all that, promotion on upward to other environments will be planned and implemented

**Comment by jonnalley** [comment]
Trying to schedule another working session for next week

**Comment by jonnalley** [comment]
Testing with AMS is complete and has been validated in `localhost` and `staging`. Targeting a final cutover on 7/10

**Comment by jonnalley** [comment]
waiting on cutover until further OCIO action around non-PIV accountholders.

**Comment by jonnalley** [comment]
Related issue is #1206 about supporting both AMS and login.gov. We're already ready to cutover/add support for any environments so this may be kinda sorta moot.

**Comment by jonnalley** [comment]
Moving ADR task to #1206 and will create a new backlog item to get onboarded to the production environment
