### ISSUE TITLE
Research whether a Revocation List is needed, or whether "User Context" (sidejacking prevention) would facilitate this need.

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#662]

**Comment by johndeange** [comment]
Discussed at Backlog Refinement Meeting:  I think both a Revocation List and Sidejacking Prevention would be useful security enhancements.

Some relevant links:

https://github.com/vimalloc/flask-jwt-extended/issues/70
https://flask-jwt-extended.readthedocs.io/en/stable/blocklist_and_token_revoking.html#jwt-revoking-blocklist

I propose that we split this tasks into 2 stories and implement both.

**Comment by jonnalley** [comment]
#2346 

#2347
