### ISSUE TITLE
Create Budget Lines

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#674]
### User Story
As an OPRE staff member, I want to create budget lines on agreements so I can know what items make up an agreement

### Acceptance Criteria
- [x] User can create a properly-formatted budget line entry that is persistently stored
- [x] User should see an indication of some kind that the creation was successful
- [x] The budget line's status should default to "Draft"

-----------------------------------------

#### UX
- [x] Outline a research plan / approach as needed
- [x] Schedule interviews with budget team
- [x] Conduct interviews with budget team
- [x] Develop a user workflow / process map of a budget line
- [x] Synthesize research findings
- [x] Explore design options
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on Sheila's feedback
- [x] Get more feedback from CORs
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

#### Dev
- [x] Software design and flow for a Budget Line Item
- [x] Decide on libraries or frameworks for forms/user input  
- [x] Fix/Improve e2e testing upgrading cypress or cypress-axe as needed @tdonaworth 
- [x] #735 - @johndeange 
- [x] #736 - @johndeange 
- [x] Remove dependency of the flask sqlalchemy plugin - @johndeange 
- [x] #737 - @tdonaworth / @fpigeonjr 
- [x] #738 - @fpigeonjr 
- [x] #739 @fpigeonjr 
- [x] #740 @fpigeonjr 
- [x] #741 @fpigeonjr 
- [x] #742 - @johndeange 
- [x] #744 @fpigeonjr 
- [x] #745 @fpigeonjr 
- [x] #746 @fpigeonjr 
- [x] #747 @fpigeonjr 
- [x] #809 - @xlorepdarkhelm
- [x] #748
- [x] #749 - @johndeange 
- [x] #750 - @johndeange 
- [x] #751 - @fpigeonjr 
- [x] #752 - @fpigeonjr 
- [x] #753 - @tdonaworth 
- [x] Populate any sample data needed
- [x] Create additional backend components (i.e. API endpoints, etc..) to accommodate the AC
- [x] #725 - Procurement shop - @xlorepdarkhelm 
- [x] #770 - Procurement shop FE - @fpigeonjr @xlorepdarkhelm 
- [x]  #818 - @tdonaworth @fpigeonjr 
- [x]  #819 - @fpigeonjr 
- [x]  #844 - @fpigeonjr  
- [x] Rounding of numbers in summary cards
- [x] off by a digit in fee calculation
- [x] NaN for 2024 dates (and beyond?)
  - 🤔can't duplicate in `localdev`

### Definition of Done Checklist
~- [ ] UI works as designed~ see #1008
- [x] OESA: Code refactored for clarity
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Build process updated
~- [ ] Documentation updated or added~
- [ ] ~~Feature flags/toggles created~~
- [x] OESA: Dependency rules followed

### Additional Context & Resources
* Some refactoring and changing of state management is tracked in #982
* "Properly-formatted" can be determined as the story is being worked. 
* Don't boil the ocean. Start basic and small, other aspects of this epic are in these stories:
    - Input validation, sanitization, enforcement of required fields, and handling of business rules for the budget line is in #675
    -Application logging of record creation and changes is in #676
    -Approval workflow/process for adding budget lines is in #677
    -Being able to copy an existing BL values to a new one (or X number) is in #678
    -Having a view of all changes to BLs aka audit log) with metadata is in #679
    -Summarizing changes at a higher level than each BL is in #680
* https://docs.google.com/document/d/1uAQmZm8DOJtLAFZHLk7oaDApAZnRJZp3do4d1FUG5a4/edit?pli=1#bookmark=id.a4c4eh83zldy
* [Drawing](https://lucid.app/lucidchart/da53e169-0ebc-4dc2-b9c1-e60e1de3ca2a/edit?referringApp=slack&shared=true&invitationId=inv_9ef4ac41-55b0-4daf-aa5a-0f465c03cd55&page=_rhFCnNf5EKf#)

**Comment by kimschulke** [comment]
Scheduled interview with a member of the budget team for Thursday 2/23 at 1pm ET

**Comment by kimschulke** [comment]
Creating a workflow to outline what we learned from the Budget Team in terms of their current process

**Comment by kimschulke** [comment]
Planning to review with OPRE on Tuesday 3/7. We have a few questions to go over and once we confirm the content/information is accurate, we can further iterate on layout, if needed.

**Comment by kimschulke** [comment]
Design is ready for development! Let us know if you have any questions

https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=144%3A5515&t=jdcahfZgoOxL88Xx-1

**Comment by jonnalley** [comment]
marked for review 5/5

**Comment by jonnalley** [comment]
A big batch of UI issues pertaining to a specific path of creating BLs is now in its own story, #1008
