### ISSUE TITLE
Request Budget Line status change from planned to executing (initial action)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#677]
### User Story
As a COR, I want to request a BL status change from Planned to Executing, so that we can begin the procurement process for budget lines we want to execute within the fiscal year

### Preconditions
* An agreement has one or more planned budget lines

### Acceptance Criteria

- [x] For now, any user role aside from a read-only user will be able to submit budget line(s) for approval. This will likely change in the future.
- [x] One or more individual budget lines on a given agreement in `planned` status can be selected for this process.
- [x] Additional team members are optional for the agreement's metadata and not required to be populated
- [x] The description field on a contract should be provided and a required field before any lines can be sent for approval to executing status
~- [ ] The user can select research type(s), topics, or populations studied for the contract.~
- [x] BLs that are submitted for approval should then transition to `In Review` and ought not be editable other than users with the System Admin role.
- [x] The user can provide text pertaining to the particular request for review/approval that would be later accessible by the reviewers/approvers.

-----------------------------------------

#### UX

- [x] Research/outline milestones or steps within executing for contracts
- [x] Determine if any additional information/documents need to be uploaded
- [x] Explore design options
- [x] Share design with team to discuss development considerations
- [x] Refine the design based on feedback
- [x] Share designs with stakeholders and other OPRE team members
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

#### Dev
**Frontend**
- [x] #1848
- [x] #1870
  - [x] Research Type
  - [x] Special Topic Population Studied
- [x] #1871
- [x] #1889

**Backend**
- [ ] Scope/User flow diagram updated or created.  Would look similar to draft->planning with the requisite differences 
- [ ] Backend additions/changes?
- [x] Maybe make a table to group the desired budget line(s) to be changed ?
  - we have these stored in a workflow package
- [x] #1890

### Definition of Done Checklist
- [x] UI works as designed (UX)
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [x] Build process updated
- [ ] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* Documents on process/workflow:
  * https://docs.google.com/document/d/1xFzX6TbPemUwfSzd83cUCRzijUQdIR_sXF-9w07Bfkg/edit
  * https://docs.google.com/document/d/1CvYMfqPOND2zCBMTVEfJ2OEg4RR2idMl4t6_XeCQ-80/edit?pli=1#bookmark=id.ye9c2thosxwm
  * https://docs.google.com/document/d/1A4WZDAHVCWzb4ungHwdjdgRQs-6ap7B_9YOGvInKdpE/edit
  * https://docs.google.com/document/d/18YDPPDbebc7bJn3XzhkKhP79YtmayL0xA0-tBz01eSM/edit
* Related to #1503
* Do we need more authz stuff and user roles in place as a pre-req first? Or a feature flag or something similar in concept in place to bypass or allow any initial user to do these approvals?
* In example, if the current date is 7/15/2023 (FY 2023), the user could select a planned budget line with a need by date of 10/14/2023 (FY 2024) because it's within 3 months from now. 
* Perhaps in a later story, emails or something will go out advising users that they need to approve something but that's not something to be addressed in this story
* Future consideration: Later we might want to lock down this action to certain users/roles such as: Project Officer (aka COR) user, team leader, DD, the budget team, or the System Admin 
* We know that each contract shop has a potentially different set of documents to use and that's handled in a separate user story
* Figma designs show things beyond the scope of this user story, In example: uploading files and editing other contract details before sending to approval, which are separate stories

**Comment by kimschulke** [comment]
In regards to the first task on outlining the milestones within executing... per our previous research with Josh, the milestones / steps / tasks have been defined as:

- Pre-solicitation - the package is sent to the Procurement Shop and they are reviewing it
- Solicitation - the package has been accepted by the contracting shop
- Evaluation - Proposals have been received from the vendors and are under review
- Pre-Award - Evaluations have been completed and the technical eval was sent to the Procurement Shop for final preparation
- Awarded - The signed award has been received and uploaded for review by the Budget Team

All procurement milestones must be checked off including who completed the step and the date it was completed

**Comment by jonnalley** [comment]
1/23

**Comment by kimschulke** [comment]
Tried to complete UI Review last week and this week, but I haven't been able to complete the tasks due to some bugs that are currently being worked out. Will come back to complete UI Review at another time.

**Comment by kimschulke** [comment]
Finally getting to UI Review on this one... a few notes/things to discuss

- We forgot to add the Cancel option for the Send to Approval workflow. Need to incorporate the exit/cancel option into Figma and Development
- The workflow for resolving errors is a little clunky and dev does not match Figma
    - In Figma, when the user clicks "edit" to resolve errors, they go to one page to edit all the agreement details
    - In Dev, when the user clicks "edit" to resolve errors, they go to step 1 in the Create Agreement wizard
    - Going to step 1 of the Create Agreement wizard is a little cumbersome. For example, if I only need to resolve an error on the Description... why do I need to go back to Step 1 and Step 2 and Step 3 of a wizard? Additionally, in the wizard, if the user clicks Save Draft, they exit the entire Send to Approval workflow which is not the intended goal... they are trying to resolve an error and get back to Send to Approval
- Now that we have SCs integrated into agreements, we need to go back and update with SCs, but this can likely be tracked in a different github issue

**Comment by jonnalley** [comment]
@kimschulke @fpigeonjr Regarding the first bullet point, I could be mistaken but the cancel option wasn't a matter of being forgotten necessarily, it's just not part of this story--not a "happy path" and not part of meeting this specific user need.

**Comment by kimschulke** [comment]
Tech/Design debt issues --
https://github.com/HHS/OPRE-OPS/issues/2097
https://github.com/HHS/OPRE-OPS/issues/2098
https://github.com/HHS/OPRE-OPS/issues/2096
