### ISSUE TITLE
Modify existing draft budget lines (within contract)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#681]
### User Story
As any OPS user, I want to update the attributes of a pre-existing draft budget line on a contract so that data in OPS is accurate and reliable.

### Preconditions
* A contract is already created and in existence with draft budget lines and no budget lines in any other status.

### Acceptance Criteria
- [x] The user can access and locate the draft contract containing the budget lines they wish to alter.
- [x] The user can choose to edit that contract's budget lines
~- [ ] The budget team, the division director (via CAN relationship), as well as any OPS user that's added as a lead or team member on the contract should be able to update any attribute of the draft BL.~ pending further discussions and work on authz and MVP scope
~- [ ] Other OPS users not in the list of users in the prior AC should not be able to edit the draft BL.~ pending further discussions and work on authz and MVP scope
- [x] User can successfully submit a change to values for the existing draft budget line and that change is persisted.
- [x] User should receive an indication of some kind that the edit was successful

-----------------------------------------

#### UX
- [ ] Identify the best way for OPS users to iterate/communicate on changes
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on feedback
- [x] Create clickable prototype
- [x] Provide design assets with annotations to developers

#### Dev
- [x] Validate this functionality is done (?) 
- ~~Update backend components to satisfy the AC~~
- ~~Build frontend interactions and components to satisfy the AC~~
- [x] Given the modified UI Designs, refactoring of the previous implementation of the Edit From should occur - tracked here: #1209 
- [x] Conduct experiment with newly-released SQLAlchemy features #1204 @johndeange 
- [x] #1274

### Definition of Done Checklist
- [ ] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- ~~Build process updated~~
-  ~~Documentation updated or added~~
-  ~~Feature flags/toggles created~~

### Additional Context & Resources
#677

**Comment by kimschulke** [comment]
Need to decide if users will see all budget lines on all agreements/projects OR if they will see just their agreements/budget lines.

Is there a need to view a catalog of all budget lines or just budget lines within each agreement?

**Comment by tdonaworth** [comment]
We need to discuss many more use-cases for this:
* What happens if the owner isn't available to make updates (vacation, emergency, etc)? Who can make edits? 
* Why can't others make changes, and then those changes be tracked in the "thread"? 
* Who should be able to delete a BLI (owner only? Lead? Admin?)

**Comment by jonnalley** [comment]
> We need to discuss many more use-cases for this:
> 
> * What happens if the owner isn't available to make updates (vacation, emergency, etc)? Who can make edits?
> * Why can't others make changes, and then those changes be tracked in the "thread"?
> * Who should be able to delete a BLI (owner only? Lead? Admin?)

This whole story needed a significant re-write given information we've learned and things we've implemented since February when this story was created. I've done so and at this point, your apt questions will be more apropos on another item and I'll incorporate them there as research that needs to be done

**Comment by kimschulke** [comment]
Current design in Figma for Edit an Agreement with Budget Lines - Follow the workflow for "user clicks edit" --
https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=3492%3A92482&t=TK07LHXHwoW4lblI-1

**Comment by fpigeonjr** [comment]
may need some clarity on this. Currently anyone is able to update DRAFT budget lines but the AC mentions group permissions which I don't think has been implemented yet.

**Comment by jonnalley** [comment]
somewhat on hold until we decide how user roles/permissions will affect the AC of in-flight stories like this one (and others)

**Comment by jonnalley** [comment]
Reviewing and discussing some alternatives to UX for this story related to the advent of #1156

**Comment by jonnalley** [comment]
moved to review on 8/3
