### ISSUE TITLE
View budget lines across agreements

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#682]
### User Story
As an OPRE budget team member, I want to view budget lines across all agreements and portfolios so I can manage the budget 

### Acceptance Criteria
- [x] The user can locate any budget line by relevant fields (searching/filtering) across all/any quarter project, agreement or portfolio
- [x] The user can discern the type of agreement a BL is related to
- [x] The user can discern the Project Officer the BL is related to via its agreement relationship
- [x] The user can discern the status, CAN, need-by date, and amount of the BL

-----------------------------------------

#### UX

- [x] Explore design options
- [x] Review previous research and identify any additional research, as needed
- [x] Share draft designs with team for internal feedback / dicussion
- [x] Share draft designs with OPRE for feedback
- [x] Refine design based on feedback

##### Frontend

- [x] #1338 - @johndeange 
- [x] #1349 - @fpigeonjr 
- [x] #1350 - @johndeange 
- [x] #1351 - @fpigeonjr 
- [x] #1409
- [x] #1407
- [x] #1352
  - [x] #1441
  - [x] #1508
- ~~#1353~~
- [x] #1354 - @fpigeonjr 
- [x] #1355 - @fpigeonjr 
- [x] #1356 - @johndeange 
- [x] #1357 - @johndeange 
  - [x] [UX Review] add tag label `Filters Applied` for Agreement filters
  - [x] [UX Review] Tags need more padding
- [x] #1358 - @johndeange 
- [x] #1359 - @johndeange 
- [x] #1511
- [x] #1523
- [x] #1529
- [x] add/update e2e tests
- [x] [UX Review] disable icons instead of hiding them in Table Rows
- [x] [Tech Debt] revisit budget line calculations after [1459](https://github.com/HHS/OPRE-OPS/pull/1459) merge

##### Backend

- [x] #1371 - @johndeange 
- [x] #1394 - @johndeange 

### Definition of Done Checklist
- [x] UI works as designed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [-] Build process updated
- [X] Documentation updated or added
- [-] Feature flags/toggles created

### Additional Context & Resources
* a BL's funding would expire at the end of the 5th fiscal year after the need by date
* #676
* #679 and #680

**Comment by tdonaworth** [comment]
Would this be related to #803

**Comment by jonnalley** [comment]
@tdonaworth unclear.  Further usability testing and research should bear this out. Today, MAPS prominently features searching for and finding individual budget lines directly as first-class data structures without first finding its attached agreement. I don't believe we know if that's actually helpful or needed yet given all the other changes OPS introduces and so we really need to validate the need for this one way or another, refine it, and prioritize, as with anything else. 

This story was likely added based on just seeing what folks do in MAPS today, perhaps as a placeholder, hence not being more fully progressed along.

**Comment by jonnalley** [comment]
Need some answers from PO on is this something we want in OPS, for BLs to exist as a first-class object outside of agreements

**Comment by jonnalley** [comment]
to follow-up on prior comments, this story could potentially benefit from re-usable React components presumably used in 803 but otherwise, it's a separate need, but not unlike it.   There are business process needs for the budget team to find, look at, and need to approach BLs at this level and not the agreement-level as well, so hence the need.

**Comment by kimschulke** [comment]
We have an updated design based on team/OPRE feedback from last week. Linked below! 

The only thing we need to add is the pagination, and a loading message in the event the dataset is taking time to load. This will be added today.

One thing to note - we decided to slim down the filters quite a bit. This is based on our conversation around filtering vs more complex reporting and whats in scope for the MVP. At this point, we are thinking its best to start simple and then once people start using OPS, we can learn more about what they need and add more filters with dynamic relationships between them (for example selecting 1 project and making the agreement options dynamic on that selection).


https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=5952-22029&mode=dev

**Comment by kimschulke** [comment]
The pagination has been added to the design. We are using the USWDS pagination component which is not really for a table/dataset. We can either implement the USWDS component underneath the table OR looking into using another component library / creating something custom for a table with pagination. Example below. Let us know what you think / whats easier or more efficient to implement --

Example from Material Design
<img width="792" alt="Screenshot 2023-08-21 at 3 48 08 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/1f38e37b-8c2a-4282-ba05-0c960c325490">

**Comment by kimschulke** [comment]
Hi, I am just reviewing the Figma compared to Dev to outline any changes needed. I noticed this page needs more work to bring the Figma design and Dev closer together. Just wanted to check-in to see if I should list out those items or if you just need more time to work on it. Let me know :)

**Comment by jonnalley** [comment]
@kimschulke yeah from looking at the frontend tasks they're not quite done with half of them. If you see some specific tasks that were checked off but still seeing an issue then yeah maybe bring those up now for sure

**Comment by fpigeonjr** [comment]
qq: @jonnalley What business rules do we need to enforce for #1352 and #1353—editing and deleting budget lines?

**Comment by jonnalley** [comment]
Answered out of band

**Comment by fpigeonjr** [comment]
added [UX Review] and [Tech Debt] tasks from SU—9/15/23
