### ISSUE TITLE
Create frontend code/UX related to the experiences of an expired log in session (due to duration of time)

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#711]

**Comment by jonnalley** [comment]
not sure if this is done or not... the parent issue is closed but I don't believe this got implemented in a nice way for the user

**Comment by johndeange** [comment]
Discussed during Backlog Refinement Meeting:  OK to close.  Currently a force log out navigates to the log in screen.  In the future, we would like to implement a countdown timer in the UI.
