### ISSUE TITLE
Create Agreement (Contract)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#775]
### User Story
As an OPRE staff member, I want to create a new contract so that I can facilitate research or program work in support of a project goal or topic.

### Acceptance Criteria
- [x] User can provide required attributes for and create an agreement (of type contract) with all required attributes that is persistently stored
- [x] User should see an indication of some kind that the creation was successful
- [x] User should not be able to create grants, IAAs, IDDAs, AAs, or direct obligations in this story

-----------------------------------------

#### UX
- [x] Conduct research as needed
- [x] Develop a user workflow / process map of an agreement, if needed
- [x] Explore design options
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

#### Dev
- [x]  #839 
- [x] Update backend model(s)
  - [x] #827 @tdonaworth 
  - [x] #828
    - [x] Move `procurement_shop` up from `BLI` into `GenericAgreement`
  - [x] #829 @tdonaworth 
  - [x] #830 @tdonaworth 
  - [x] #859 @tdonaworth
- [x] Update/add backend business logic
  - [x] #831
  - [x] #832 @tdonaworth 
- [x] #847 @tdonaworth 
  - will consist of some refactoring of `CreateBudgetLine` page components, to make the more reusable. 
- [x] Create frontend components
  - [x] #833 @tdonaworth 
  ~~#834 - ignore~~
  - [x] #835 @tdonaworth 
  - [x] #836 - @xlorepdarkhelm 
  - [x] #837 - @fpigeonjr 
    - [x] Create Project Officer selection (pull from Users endpoint for now)
    - [x] Create Team Member selection Component
    - [x] Create Team Member Added component, with removable tagged users.
  - [x] Project Summary Card: remove Project Officer and add Description - @fpigeonjr 
  - [x] Step 2 Description: Make a text-box and add state - @fpigeonjr 
  - [x] Step 2: Add Product Service Code Summary Box - @fpigeonjr 
  - [x] Step 2: ~~Add Incumbent ComboBox~~ Change to Text Field - @fpigeonjr 
  - [x] Step 2: Makes notes a text-box and add state - @fpigeonjr 
  - [x] Step 2: Add Save Draft Button
  - [x] Step 3: Copy over create budget lines components and slice methods - @fpigeonjr 
  - [x] Step 3: Add Modals and Alert messages for create edit, delete BLIs and for returning to step 2 - @fpigeonjr 
  - [x] Add cancel Modal and reset state - @fpigeonjr 
  - [x] Step 3: Step Indicator is not correct - @fpigeonjr 
  - [x] All Steps: Ensure state is set on form elements when navigating between steps - @fpigeonjr 
  - ~~#838~~
- [x] #886
- [x] UI Review tasks - @fpigeonjr 
  - [x] #994
  - [x] #1006
  - [x] #1007
  - [x] #1009
  
- ~~Update breadcrumbs/navigation as necessary~~ Hansel and Grettle know how to get home. 

### Definition of Done Checklist
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [x] Build process updated
- [ ] Documentation updated or added
~- [ ] Feature flags/toggles created~

### Additional Context & Resources
* The low number of AC is intentional. This story should be  a very simple and happy path.
* There are contract-specific attributes that will need to be added on to both the agreement and any BLs that belong to the agreement.
* [Drawing](https://app.diagrams.net/#G1LUqllh-1xXUYdcvkksfiChJff75WQn9h)

#774

**Comment by tdonaworth** [comment]
![image](https://user-images.githubusercontent.com/56687505/229868768-8eb5dc9f-dc67-4c3f-9b3b-8b6fd8eea6c4.png)

**Comment by jonnalley** [comment]
> ![image](https://user-images.githubusercontent.com/56687505/229868768-8eb5dc9f-dc67-4c3f-9b3b-8b6fd8eea6c4.png)

where's the Co-pilot feature to turn this screenshot into a PR ?

**Comment by kimschulke** [comment]
Notes from UI Review: https://docs.google.com/document/d/1Poj3OAnXZY3518gUNlbUoAyaoZjJkqUghcRTxOFKWTY/edit

**Comment by jonnalley** [comment]
marked for review 5/5

**Comment by fpigeonjr** [comment]
added a few UI Review stories

**Comment by kimschulke** [comment]
@fpigeonjr  

On step 1 to select the project - at the bottom of the page where it provides the option to "Add New Project" - the word "or" should be the same grey color as the lines to either side of the word. Hex is #A9AEB1. It is currently blue in Staging.

<img width="1006" alt="Screenshot 2023-05-12 at 12 08 08 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/e1855cc3-e509-448e-a651-99c9d38f7ff7">

**Comment by kimschulke** [comment]
Light blue rectangle padding around each name in the Team Member List could be increased a bit. Additionally, the x icon to delete a team member does not appear to be the same x icon we are using from USWDS (?)

Staging:
<img width="1092" alt="Screenshot 2023-05-12 at 12 16 07 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/5b57e5b5-5c28-4311-9f20-1c0e94a11a8b">

Figm
<img width="695" alt="Screenshot 2023-05-12 at 12 18 09 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/c31c108c-6886-4814-8590-f0c3c8a2a61f">
a:

**Comment by jonnalley** [comment]
prior two comments I added as a `task` to this story and a separate `bug` respectively. Feedback/disagreement welcome.

**Comment by fpigeonjr** [comment]
> Light blue rectangle padding around each name in the Team Member List could be increased a bit. Additionally, the x icon to delete a team member does not appear to be the same x icon we are using from USWDS (?)

@jonnalley. Would you know if we have a user-story for this task?

**Comment by jonnalley** [comment]
@fpigeonjr I sure do, it's #995

**Comment by fpigeonjr** [comment]
> @fpigeonjr I sure do, it's #995

Thanks @jonnalley , glad I asked!
