### ISSUE TITLE
Submit an Agreement w/ BL to Approval (submitter)(to Planned)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#791]
### User Story
As a COR or team lead, I want to submit an agreement with budget lines to go through an approval process so that necessary accountabilities and controls can be maintained over financial data.

### Precondition
* A newly-submitted agreement with budget lines should be stored but considered in an unapproved (Draft) state

### Acceptance Criteria
- [x] User can access a draft agreement that they want to submit for approval
~- [ ] User is required to fill in all required fields before they're permitted to submit for approval~ moved to #675
~- [ ] User is aware of and has proper indications of what fields will be required for submitting to approval~ moved to #675
- [ ] User can actually execute the submission of the draft agreement (with its BLs) and receive confirmation of the same.
- [x]  Users who submitted the agreement for approval should be able to see the status of the approval workflow.

-----------------------------------------

#### UX
- [x] Explore design options
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

#### Dev

- [x] #891
  - [x] Create a Agreement Summary Card Component
  - [x] Create (or reuse) BLI Funding Table Component
  - [x] Create/Add BLI Funding Totals Cards
  - [x] Add Edit Button
  - [x] Add Send-For-Approval Button 
- [x] #966
  - [x] execute `PUT` `/budget-line-items` to update the status to `UNDER_REVIEW`
- [x] Update breadcrumbs/navigation as necessary
- [x] Minor UI cleanup #1069 - @fpigeonjr 

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
~- [ ] Feature flags/toggles created~

### Additional Context & Resources
* Depending on when #676 happens, should logging of the approval events be part of this story or included as part of that one ?
* Do we need more authz stuff and user roles in place as a pre-req first?
* Perhaps in a later story, emails or something will go out advising users that they need to approve something but that's not something to be addressed in this story (captured in #965 ?)

**Comment by kimschulke** [comment]
@fpigeonjr No rush, but just let us know when this is ready to review. Thank you!

**Comment by fpigeonjr** [comment]
Wonder if validation tasks would be covered in #675?

**Comment by jonnalley** [comment]
@fpigeonjr fair point, updated.  @kimschulke @andressacurvelo what say you on the UI review for this story? What's left here ?

**Comment by kimschulke** [comment]
Instruction text needs a small edit -- 

**Currently in Staging**
"Please review the agreement below **or** edit any information if necessary."

**Figma Design**
Please review the agreement below **and** edit any information if necessary. Send to Approval will send the agreement to your Division Director to review for Planned Status.

**Comment by kimschulke** [comment]
Also, the spacing for Procurement Shop - There should be a space before and after the hyphen

**Currently in Staging**
Product Service Center-Fee Rate: 0%

**Figma Design**
DOI - Fee Rate: 4.8%

**Comment by kimschulke** [comment]
And, the Review Page is missing the list of Team Members

**Comment by fpigeonjr** [comment]
@jonnalley, would it be ok to add all UI review comments into a user-story and I could take a look at them soon.

**Comment by kimschulke** [comment]
Looks good, thanks!
