### ISSUE TITLE
Search/filter all agreements

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#802]
### User Story
As an OPRE staff member, I want to find a particular agreement out of the full set of agreements so I can access the information I need.

### Acceptance Criteria
- [ ] User can search or filter agreements 
- [ ] User can access the full details of a particular agreement they want to see more details of

-----------------------------------------

#### UX
- [ ] Conduct research as needed
- [ ] Explore design options
- [ ] Share designs with stakeholders and other OPRE team members for feedback
- [ ] Refine the design based on feedback
- [ ] Provide design assets with annotations to developers

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

**Comment by tdonaworth** [comment]
Could we use the resulting page from #803 to perform these tasks? We'd still need the addition of an `Agreement Detail` page; which could mirror the current `Approve Agreement` page for now. Making either the `Agreement` Title clickable, or adding an additional icon on the right to "View Details" ?  @kimschulke @andressacurvelo @jonnalley

**Comment by jonnalley** [comment]
@kimschulke Given the title and content change that occurred to #803, it seems that #802 and #803 are now redundant with how I'm reading it.  The original intent was to be able to easily see all agreements that a user was added to and then a separate story to find agreements based on any other criteria, even if it wasn't via a "filter" per se.

Can we discuss that further ?

**Comment by jonnalley** [comment]
The first AC is intentional vague as to give leeway on scope that we bring in to this story vs. something that we defer to a future story where more features and concepts are built out

**Comment by jonnalley** [comment]
After discussion on 6/12, we think this is no longer needed in light of #803
