### ISSUE TITLE
Create user flow diagram for creating a Contract Agreement, outline state objects needed.

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#839]
Create a User Flow diagram for creating a Contract Agreement

BLI Flow Ref: https://lucid.app/lucidchart/da53e169-0ebc-4dc2-b9c1-e60e1de3ca2a/edit?referringApp=slack&shared=true&invitationId=inv_9ef4ac41-55b0-4daf-aa5a-0f465c03cd55&page=0_0#
High Level Flow Ref: https://docs.google.com/document/d/1CvYMfqPOND2zCBMTVEfJ2OEg4RR2idMl4t6_XeCQ-80/edit?pli=1

**Comment by tdonaworth** [comment]
@xlorepdarkhelm @johndeange @fpigeonjr @kimschulke @andressacurvelo @jonnalley - Please review the specific steps, and let me know if we're missing anything, thanks!
[OPRE OPS User Flow](https://app.diagrams.net/#G1LUqllh-1xXUYdcvkksfiChJff75WQn9h)

**Comment by xlorepdarkhelm** [comment]
> @xlorepdarkhelm @johndeange @fpigeonjr @kimschulke @andressacurvelo @jonnalley - Please review the specific steps, and let me know if we're missing anything, thanks! [OPRE OPS User Flow](https://app.diagrams.net/#G1LUqllh-1xXUYdcvkksfiChJff75WQn9h)

I don't know about anyone else, but I can't see the user flow. When I try to connect my Google account to it I am getting an error.

**Comment by jonnalley** [comment]
> I don't know about anyone else, but I can't see the user flow. When I try to connect my Google account to it I am getting an error:
> 

It's still working fine for me. I'm happy to look at it with you if it might help.

**Comment by jonnalley** [comment]
@tdonaworth @fpigeonjr @johndeange @xlorepdarkhelm I would assume at this point any feedback would have been given and will close this task accordingly. Please object and/or re-open if you feel differently
