### ISSUE TITLE
Create a research project

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#840]
### User Story
As a COR or team lead, I want to create a new research project to have OPRE efforts properly managed and documented.

### Acceptance Criteria
- [x] A research project is created and persisted with the necessary attributes provided at the time of creation

-----------------------------------------

#### UX
- [x] Conduct research as needed
- [x] Explore design options
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

#### Dev

- [x] #849  @johndeange 
- [x] #883 @xlorepdarkhelm 
- [x] #946 @johndeange 

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
~- [ ] Documentation updated or added~
~- [ ] Feature flags/toggles created~

### Additional Context & Resources
* [Drawing](https://app.diagrams.net/#G1LUqllh-1xXUYdcvkksfiChJff75WQn9h)

**Comment by kimschulke** [comment]
Notes from UI Review; https://docs.google.com/document/d/1Poj3OAnXZY3518gUNlbUoAyaoZjJkqUghcRTxOFKWTY/edit

**Comment by jonnalley** [comment]
marked for review 5/5

**Comment by tdonaworth** [comment]
All is `[x]` is it done? @jonnalley
