### ISSUE TITLE
Edit Draft Agreement Metadata

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#856]
### User Story
As an OPRE COR or team lead, I want to alter some attributes of an agreement itself before it is in planned status.

### Preconditions
No budget lines are in "planned" status and thusly the agreement has not previously been approved. 

### Acceptance Criteria
- [ ] User can change any agreement-level metadata and have the changes persistently stored

-----------------------------------------

#### UX
- [x] Explore design options
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

#### Dev
***Backend***
- [x] #1017
- [x] #1043 @stevtek 
  - [x] Create Business Rules (gherkin features) for required field checks.
  - [x] Ensure Business Rules for metadata are checked for validity.

***Frontend***
- [x] #1088 - @stevtek @fpigeonjr 
- [x] #1115  - @fpigeonjr 
- [x] wire up pencil on agreements list
- [x] wire up agreement review edit button
- [x] Edit Agreement Design v2
   - [x] Agreement Details page #1156 <-- Lots of stuff in here 😉 
   - [x] Edit Agreement Details from/in details page
     - [x] #1209
   - [x] change edit links to new edit page (instead of wizard)

### Definition of Done Checklist
- [x] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] ~Build process updated~
- [x] Documentation updated or added
- [x] ~Feature flags/toggles created~

### Additional Context & Resources
* Editing an agreement's budget lines is a separate story #681
* reduce value - changes tracked. contract mods?
* change metadata is a "mod" i.e. vendor, etc... at some point in the contract's status/lifecycle
* Once a contract is awarded, the PoP. Contract number, type, procurement shop, cannot be edited.
* Once BLs go into "in execution", a budget officer should change metadata, not other users

**Comment by kimschulke** [comment]
Designs for edit workflow here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=3492%3A92482&t=xWoXyHK5N1RTxw0l-1

**Comment by fpigeonjr** [comment]
> Ensure required fields are enforced.
wonder if we need to enforce required fields just to edit an Agreement. I was under the impression that required fields were only needed before sending to review?

**Comment by jonnalley** [comment]
@fpigeonjr yeah this gets back to what "status" the agreement/its underlying BLs are in.....hmmm.  apropos to what we were discussing this morning

**Comment by jonnalley** [comment]
@fpigeonjr but since this story is for draft, then yeah, there wouldn't be anything enforced. I don't know why that task is in there then

**Comment by jonnalley** [comment]
@fpigeonjr well the title would still be required IIRC

**Comment by fpigeonjr** [comment]
> well the title would still be required IIRC

👍🏿thanks @jonnalley for the clarification on this.

**Comment by stevtek** [comment]
You can now edit the agreement and the budget lines but without restrictions on status.  This and #681 state pre-conditions on status.  What do I need to do at this point to finish up these two while "status" is a moving target?
Does the UI need to stop users from editing the agreement or budget lines under any conditions (for now)?

**Comment by jonnalley** [comment]
somewhat on hold until we decide how user roles/permissions will affect the AC of in-flight stories like this one (and others)

**Comment by jonnalley** [comment]
Reviewing and discussing some alternatives to UX for this story related to the advent of #1156

**Comment by kimschulke** [comment]
Edit agreement workflow looks good! User feedback validated it was clear and easy to understand. Internal team idea for future improvement may include to re-locating the edit button, if there is a way to move it closer to the content you are actually editing.

**Comment by jonnalley** [comment]
moved to review on 8/3
