### ISSUE TITLE
[2] Set up Flake8

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#87]
### Goals
* Set up Flake8 as a linter to check for Python code quality

### Tasks
- [ ]  Update CircleCI config file to run Flake8 as part of CI/CD

### Additional COntext
* Dependent on #86

**Comment by alexsoble** [comment]
@carjug We may need to do #86 first before we can build flake8 into the CI, but we could always add some initial config for flake8 with instructions for running it locally in the meantime!

**Comment by carjug** [comment]
@alexsoble Yeah I was just realizing that! I'll get it setup locally first and then see where the CircleCI ticket is at.

**Comment by alexsoble** [comment]
Sounds good! I'll pull in the CI ticket because I think getting that set up will unblock a lot of things!
