### ISSUE TITLE
Build frontend components for Create New Project

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#883]
- [x] Create ProjectTypeSelect component
- [x] Create Nickname/Acronym Text Field
- [x] Create Project Title Text Field
- [x] Create Description Text Block
- [x] Create Project State objects (Slice)
- [x] Wire up to POST 

![image](https://user-images.githubusercontent.com/56687505/234065608-9806bdc7-39e7-4229-a530-0c05f11556a3.png)

**Comment by AmareB441** [comment]
This is for test
