### ISSUE TITLE
When new Agreements are created, the `Agreement` select in CreateBudgetLine flow, isn't updated.

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#896]
## Expected Behavior

The select input should be updated to show all newly created agreements.

## Current Behavior

Only shows the initial agreements.

## Possible Cause

Tim broke it maybe?

## Steps to Reproduce

1. Navigate to /agreements/create
2. Complete creating a New Agreement (step 2)
3. Navigate to /budget-lines/create
4. Select the matching Project, that you added the new Agreement to.
5. Open the Agreement select, it should have more than the initial list.

**Comment by johndeange** [comment]
Unable to reproduce.  Sent Slack message to team to verify.

**Comment by tdonaworth** [comment]
Was resolved with another bug fix already.
