### ISSUE TITLE
`NaN/NaN/NaN` Need By date 

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#898]
When editing a blank budget line item and leaving date blank, it causes a `NaN/NaN/NaN` in the Need By date in the table below. 

## Expected Behavior

Even when editing a blank BL, need By date in the table should remain blank if the date is in fact blank, or the proper date values shown properly if not blank.

## Current Behavior
Need By date in the table shows `NaN/NaN/NaN`, see above

## Possible Cause

Bug is probably in the `<PreviewTable />` or the `</CreateBudgetLinesForm />` components.
## Steps to Reproduce

1. add a blank BLI
1. edit anything but leave date fields empty
1. Click on Update Budget Line button
1. Need By field will show `NaN/NaN/NaN`

<img width="984" alt="image" src="https://user-images.githubusercontent.com/4629398/234670002-d9098d17-4fc0-48c2-97c7-23498d2bcaf0.png">

**Comment by johndeange** [comment]
Fixed.
