### ISSUE TITLE
<TeamMemberSelect/> does not clear once team member is selected

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#909]
`<TeamMemberSelect/>` does not clear once team member is selected
## Expected Behavior

Input and dropdown should clear once a team member is selected.
## Current Behavior

Team member is added and the input is set to the first team member
## Possible Cause

We're hacking the uswds comboBox so could be forcing it to do something it wasn't supposed to do.
## Steps to Reproduce

1. Goto Create an Agreement
2. On step two select a Team Member
3. Tab to the next input field `Notes`
4. Team Member Select's input will change to the first team member in the list<img width="646" alt="SCR-20230427-kywm" src="https://user-images.githubusercontent.com/4629398/234939055-d0bee3dd-9e78-4278-a820-d978b27005a1.png">

**NOTE:** Can be cleared by clicking on the `x-button` next to the team member

**Comment by fpigeonjr** [comment]
not needed for May demo

**Comment by fpigeonjr** [comment]
just tested on main and this is still an issue

**Comment by jonnalley** [comment]
As @johndeange mentioned today elsewhere, there is discussion and review to replace this component with another drop-down component that in so doing, will subsume the existence of this bug. Stay tuned
