### ISSUE TITLE
[4] Determine CI/CD automation process

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#96]
### Goals
* Determine what we want our automatic deployment rules to be for when we set up CircleCI (#86 )

### Tasks
- [ ] Determine automation rules for where to push and when (esp given multiple devs pushing changes)

### Additional Context
* Related to #86

**Comment by alexsoble** [comment]
@amymok @carjug How do we see ourselves tackling this one as an eng team? I would be happy to pick up this card and sketch out CI/CD flows. 

Some of the Tasks listed, like managing dependencies, seem like they might be better as separate issues. 

@amymok — feel free to assign this to me if you want me to push it forward, we can also discuss tomorrow during eng cowork.

**Comment by amymok** [comment]
Thanks for picking this up @alexsoble.  Yes, if you can start it, and we can start talking about what you have and co-work on it some more together tomorrow!

**Comment by carjug** [comment]
Yeah I agree with Amy! Let's talk about it tomorrow during co-work!

**Comment by alexsoble** [comment]
During eng cowork we decided we could safely break the sub-tasks here into separate issues, doing that now!

**Comment by alexsoble** [comment]
Broke out the settings task into #123 and added some notes.

**Comment by alexsoble** [comment]
Broke the Python dependencies task into #124 and added some notes.

**Comment by ninamak** [comment]
@alexsoble Are #123 and #124 supposed to get added to this cycle, or are they awaiting prioritization for another cycle?

**Comment by alexsoble** [comment]
I think we should add them to this cycle! 

I got a little bit confused about how to do that on the GitHub board. Maybe in a future cowork we could walk the board together?

**Comment by ninamak** [comment]
Definitely!  For now, I'll add them to the bottom of the To Do column and leave it to you to drag it up to the appropriate spot.
