### ISSUE TITLE
DevEx: Refactor StepCreateAgreement.jsx

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#964]
### Goals

Refactor `StepCreateAgreement.jsx`: refactor state, look for code/components that can be reused, etc.

### Tasks
- [x] #1047
- [x] check Cancel/Go Back states in workflow

### Additional Context
* 

### Resources
*

**Comment by jonnalley** [comment]
how many rounds total do you think this will take ?

**Comment by fpigeonjr** [comment]
We may want to consider replacing RTK slice for React Context like we did on the create budget lines workflow to be consistent on how we handle state across workflows.

**Comment by fpigeonjr** [comment]
> We may want to consider replacing RTK slice for React Context like we did on the create budget lines workflow to be consistent on how we handle state across workflows.

Created a task for this effort.
